import { Weapon, WeaponId } from "./weapon-types"

const weaponsMap: Record<WeaponId, Weapon> = {
  "10mm": {
    id: "10mm",
    label: "Pistolet 10mm",
    img: "https://vignette.wikia.nocookie.net/fallout/images/c/c8/Fallout4_10mm_pistol.png/revision/latest/scale-to-width-down/242?cb=20170115061838",
    damageType: "physical",
    damageBasic: "2D6+3",
    damageBurst: null,
    ammoType: "10mm",
    range: 70,
    magazine: 12,
    ammoPerShot: 1,
    ammoPerBurst: null,
    basicApCost: 5,
    specialApCost: 7,
    minStrength: 2,
    place: 1,
    weight: 1,
    value: 450,
    frequency: 5,
    skill: "lightMedWeapons",
    knowledges: ["kFirearms", "kOneHandedWeapons"],
    tags: ["arme légère", "arme à feu", "pistolet"]
  },
  p220: {
    id: "p220",
    label: "Sig Sauer P220",
    img: "https://vignette.wikia.nocookie.net/fallout/images/2/20/Tactics_p220_sig_sauer.png/revision/latest?cb=20130109144107",
    damageType: "physical",
    damageBasic: "2D6+1",
    damageBurst: null,
    ammoType: "9mm",
    range: 80,
    magazine: 8,
    ammoPerShot: 1,
    ammoPerBurst: null,
    basicApCost: 4,
    specialApCost: 6,
    minStrength: 2,
    place: 1,
    weight: 1,
    value: 300,
    frequency: 5,
    skill: "lightMedWeapons",
    knowledges: ["kFirearms", "kOneHandedWeapons"],
    tags: ["arme légère", "arme à feu", "pistolet"]
  },
  mauserHSI: {
    id: "mauserHSI",
    label: "Mauser HSI",
    img: "https://vignette.wikia.nocookie.net/fallout/images/a/ac/Fo1_9mm_Mouser.png/revision/latest?cb=20110207042627",
    damageType: "physical",
    damageBasic: "2D6+2",
    damageBurst: null,
    ammoType: "9mm",
    range: 60,
    magazine: 7,
    ammoPerShot: 1,
    ammoPerBurst: null,
    basicApCost: 4,
    specialApCost: 6,
    minStrength: 2,
    place: 1.5,
    weight: 1.5,
    value: 700,
    frequency: 2,
    skill: "lightMedWeapons",
    knowledges: ["kFirearms", "kOneHandedWeapons"],
    tags: ["arme légère", "arme à feu", "pistolet"]
  },
  berettaM92FS: {
    id: "berettaM92FS",
    label: "Beretta M92FS",
    img: "https://vignette.wikia.nocookie.net/fallout/images/e/ea/Tactics_9mm_m9fs_beretta.png/revision/latest?cb=20130111180102",
    damageType: "physical",
    damageBasic: "2D6+5",
    damageBurst: null,
    ammoType: "9mm",
    range: 80,
    magazine: 15,
    ammoPerShot: 1,
    ammoPerBurst: null,
    basicApCost: 4,
    specialApCost: 6,
    minStrength: 2,
    place: 1,
    weight: 1,
    value: 600,
    frequency: 5,
    skill: "lightMedWeapons",
    knowledges: ["kFirearms", "kOneHandedWeapons"],
    tags: ["arme légère", "arme à feu", "pistolet"]
  },
  browningHP: {
    id: "browningHP",
    label: "Browning HP",
    img: "https://vignette.wikia.nocookie.net/fallout/images/2/2c/Tactics_browning_hp.png/revision/latest?cb=20130109141346",
    damageType: "physical",
    damageBasic: "2D6+7",
    damageBurst: null,
    ammoType: "9mm",
    range: 70,
    magazine: 13,
    ammoPerShot: 1,
    ammoPerBurst: null,
    basicApCost: 4,
    specialApCost: 6,
    minStrength: 2,
    place: 1,
    weight: 1,
    value: 800,
    frequency: 5,
    skill: "lightMedWeapons",
    knowledges: ["kFirearms", "kOneHandedWeapons"],
    tags: ["arme légère", "arme à feu", "pistolet"]
  },
  colt45: {
    id: "colt45",
    label: "Colt 45",
    img: "https://vignette.wikia.nocookie.net/fallout/images/f/f3/.45_Auto_pistol_with_the_improved_sights_modification.png/revision/latest/scale-to-width-down/340?cb=20110520154333",
    damageType: "physical",
    damageBasic: "2D6+9",
    damageBurst: null,
    ammoType: "45",
    range: 70,
    magazine: 13,
    ammoPerShot: 1,
    ammoPerBurst: null,
    basicApCost: 4,
    specialApCost: 6,
    minStrength: 3,
    place: 1,
    weight: 1,
    value: 1000,
    frequency: 3,
    skill: "lightMedWeapons",
    knowledges: ["kFirearms", "kOneHandedWeapons"],
    tags: ["arme légère", "arme à feu", "pistolet"]
  },
  desertEagle: {
    id: "desertEagle",
    label: "Desert Eagle",
    img: "https://vignette.wikia.nocookie.net/fallout/images/e/e0/Fo1_Desert_Eagle.png/revision/latest?cb=20110207040751",
    damageType: "physical",
    damageBasic: "3D6+3",
    damageBurst: null,
    ammoType: "44",
    range: 150,
    magazine: 8,
    ammoPerShot: 1,
    ammoPerBurst: null,
    basicApCost: 5,
    specialApCost: 7,
    minStrength: 3,
    place: 1,
    weight: 1.5,
    value: 1700,
    frequency: 2,
    skill: "lightMedWeapons",
    knowledges: ["kFirearms", "kOneHandedWeapons"],
    tags: ["arme légère", "arme à feu", "pistolet"]
  },
  sigSauer338: {
    id: "sigSauer338",
    label: "Sig Sauer 338",
    img: "https://vignette.wikia.nocookie.net/fallout/images/8/81/FNV_12%2C7mm_Pistol.png/revision/latest/scale-to-width-down/242?cb=20110208201225",
    damageType: "physical",
    damageBasic: "3D6+12",
    damageBurst: null,
    ammoType: "14mm",
    range: 120,
    magazine: 6,
    ammoPerShot: 1,
    ammoPerBurst: null,
    basicApCost: 5,
    specialApCost: 7,
    minStrength: 3,
    place: 1,
    weight: 2,
    value: 2500,
    frequency: 1,
    skill: "lightMedWeapons",
    knowledges: ["kFirearms", "kOneHandedWeapons"],
    tags: ["arme légère", "arme à feu", "pistolet"]
  },
  "223Auto": {
    id: "223Auto",
    label: ".223 Auto",
    img: "https://vignette.wikia.nocookie.net/fallout/images/5/58/Fo1_.223_Pistol.png/revision/latest?cb=20110211035055",
    damageType: "physical",
    damageBasic: "3D6+15",
    damageBurst: null,
    ammoType: "223",
    range: 120,
    magazine: 5,
    ammoPerShot: 1,
    ammoPerBurst: null,
    basicApCost: 4,
    specialApCost: 6,
    minStrength: 3,
    place: 1,
    weight: 1,
    value: 3500,
    frequency: 1,
    skill: "lightMedWeapons",
    knowledges: ["kFirearms", "kOneHandedWeapons"],
    tags: ["arme légère", "arme à feu", "pistolet"]
  },
  "44Magnum": {
    id: "44Magnum",
    label: ".44 Magnum",
    img: "https://vignette.wikia.nocookie.net/fallout/images/8/83/.44_magnum_revolver_%28Fallout_New_Vegas%29.png/revision/latest/scale-to-width-down/242?cb=20110208183603",
    damageType: "physical",
    damageBasic: "3D6+2",
    damageBurst: null,
    ammoType: "44",
    range: 80,
    magazine: 6,
    ammoPerShot: 1,
    ammoPerBurst: null,
    basicApCost: 4,
    specialApCost: 6,
    minStrength: 3,
    place: 1,
    weight: 1,
    value: 1500,
    frequency: 4,
    skill: "lightMedWeapons",
    knowledges: ["kFirearms", "kOneHandedWeapons"],
    tags: ["arme légère", "arme à feu", "revolver"]
  },
  revolverCasul: {
    id: "revolverCasul",
    label: "Revolver Casull",
    img: "https://vignette.wikia.nocookie.net/fallout/images/2/2a/Tactics_casull_revolver.png/revision/latest?cb=20130109141637",
    damageType: "physical",
    damageBasic: "3D6+4",
    damageBurst: null,
    ammoType: "45",
    range: 100,
    magazine: 6,
    ammoPerShot: 1,
    ammoPerBurst: null,
    basicApCost: 5,
    specialApCost: 7,
    minStrength: 3,
    place: 1,
    weight: 1,
    value: 2000,
    frequency: 3,
    skill: "lightMedWeapons",
    knowledges: ["kFirearms", "kOneHandedWeapons"],
    tags: ["arme légère", "arme à feu", "revolver"]
  },
  smithWessonM29: {
    id: "smithWessonM29",
    label: "Smith & Wesson M29",
    img: "https://vignette.wikia.nocookie.net/fallout/images/e/ec/Tactics_44_m29_revolver.png/revision/latest?cb=20130109144234",
    damageType: "physical",
    damageBasic: "3D6+6",
    damageBurst: null,
    ammoType: "44",
    range: 120,
    magazine: 6,
    ammoPerShot: 1,
    ammoPerBurst: null,
    basicApCost: 5,
    specialApCost: 7,
    minStrength: 3,
    place: 1,
    weight: 1,
    value: 2300,
    frequency: 3,
    skill: "lightMedWeapons",
    knowledges: ["kFirearms", "kOneHandedWeapons"],
    tags: ["arme légère", "arme à feu", "revolver"]
  },
  skorpion: {
    id: "skorpion",
    label: "Skorpion",
    img: "https://vignette.wikia.nocookie.net/fallout/images/a/a8/Tactics_scorpio.png/revision/latest?cb=20130110130755",
    damageType: "physical",
    damageBasic: "2D6+2",
    damageBurst: "5D6+5",
    ammoType: "9mm",
    range: 200,
    magazine: 20,
    ammoPerShot: 1,
    ammoPerBurst: 4,
    basicApCost: 4,
    specialApCost: 6,
    minStrength: 3,
    place: 1.5,
    weight: 2,
    value: 4500,
    frequency: 3,
    skill: "lightMedWeapons",
    knowledges: ["kFirearms"],
    tags: ["arme légère", "arme à feu", "pistolet mitrailleur"]
  },
  walterMpl: {
    id: "walterMpl",
    label: "Walter MPL",
    img: "https://vignette.wikia.nocookie.net/fallout/images/3/33/Tactics_walther_mpl.png/revision/latest?cb=20130110132823",
    damageType: "physical",
    damageBasic: "2D6+3",
    damageBurst: "5D6+6",
    ammoType: "9mm",
    range: 200,
    magazine: 32,
    ammoPerShot: 1,
    ammoPerBurst: 4,
    basicApCost: 4,
    specialApCost: 6,
    minStrength: 4,
    place: 2,
    weight: 3,
    value: 5000,
    frequency: 3,
    skill: "lightMedWeapons",
    knowledges: ["kFirearms", "kOneHandedWeapons"],
    tags: ["arme légère", "arme à feu", "pistolet mitrailleur"]
  },
  HKMP9: {
    id: "HKMP9",
    label: "H&K MP9",
    img: "https://vignette.wikia.nocookie.net/fallout/images/7/77/Fo1_10mm_SMG.png/revision/latest?cb=20110211035545",
    damageType: "physical",
    damageBasic: "2D6+4",
    damageBurst: "5D6+8",
    ammoType: "9mm",
    range: 50,
    magazine: 30,
    ammoPerShot: 1,
    ammoPerBurst: 5,
    basicApCost: 5,
    specialApCost: 7,
    minStrength: 3,
    place: 1.5,
    weight: 2,
    value: 5300,
    frequency: 2,
    skill: "lightMedWeapons",
    knowledges: ["kFirearms", "kOneHandedWeapons"],
    tags: ["arme légère", "arme à feu", "pistolet mitrailleur"]
  },
  uzi: {
    id: "uzi",
    label: "Uzi",
    img: "https://vignette.wikia.nocookie.net/fallout/images/7/70/Tactics_uzi.png/revision/latest?cb=20130110132332",
    damageType: "physical",
    damageBasic: null,
    damageBurst: "5D6+12",
    ammoType: "9mm",
    range: 200,
    magazine: 25,
    ammoPerShot: null,
    ammoPerBurst: 5,
    basicApCost: 6,
    specialApCost: null,
    minStrength: 4,
    place: 2,
    weight: 4,
    value: 6000,
    frequency: 2,
    skill: "lightMedWeapons",
    knowledges: ["kFirearms", "kOneHandedWeapons"],
    tags: ["arme légère", "arme à feu", "pistolet mitrailleur"]
  },
  p90: {
    id: "p90",
    label: "FN P90c",
    img: "https://vignette.wikia.nocookie.net/fallout/images/3/38/Fo2_H%26K_P90c.png/revision/latest?cb=20110308054325",
    damageType: "physical",
    damageBasic: "2D6+7",
    damageBurst: "5D6+14",
    ammoType: "5_56mm",
    range: 200,
    magazine: 50,
    ammoPerShot: 1,
    ammoPerBurst: 4,
    basicApCost: 4,
    specialApCost: 6,
    minStrength: 4,
    place: 2,
    weight: 3,
    value: 6500,
    frequency: 1,
    skill: "lightMedWeapons",
    knowledges: ["kFirearms", "kTwoHandedWeapons"],
    tags: ["arme légère", "arme à feu", "pistolet mitrailleur"]
  },
  pkk12: {
    id: "pkk12",
    label: "Gauss PKK12",
    img: "https://vignette.wikia.nocookie.net/fallout/images/f/f3/Fo2_Gauss_Pistol.png/revision/latest?cb=20110208075442",
    damageType: "physical",
    damageBasic: "4D6+15",
    damageBurst: null,
    ammoType: "ec2mm",
    range: 200,
    magazine: 12,
    ammoPerShot: 1,
    ammoPerBurst: null,
    basicApCost: 4,
    specialApCost: 6,
    minStrength: 3,
    place: 1,
    weight: 0.5,
    value: 20000,
    frequency: 0,
    skill: "lightMedWeapons",
    knowledges: ["kOneHandedWeapons"],
    tags: ["arme légère", "pistolet", "spécial"]
  },
  acidPistol: {
    id: "acidPistol",
    label: "Pistolet à acide",
    img: "https://vignette.wikia.nocookie.net/fallout/images/f/f2/Acidsoaker.png/revision/latest/scale-to-width-down/242?cb=20160826065554",
    damageType: "other",
    damageBasic: "3D6+2",
    damageBurst: null,
    ammoType: "hci",
    range: 10,
    magazine: 10,
    ammoPerShot: 1,
    ammoPerBurst: null,
    basicApCost: 5,
    specialApCost: null,
    minStrength: 2,
    place: 1.5,
    weight: 1,
    value: 3500,
    frequency: 3,
    skill: "lightMedWeapons",
    knowledges: ["kOneHandedWeapons"],
    tags: ["arme légère", "pistolet", "spécial"]
  },
  grenadePistol: {
    id: "grenadePistol",
    label: "Pistolet à grenades",
    img: "https://vignette.wikia.nocookie.net/fallout/images/0/06/Tactics_grenade_pistol.png/revision/latest?cb=20130111174830",
    damageType: "physical",
    damageBasic: "5D6",
    damageBurst: null,
    ammoType: "40mm",
    range: 20,
    magazine: 1,
    ammoPerShot: 1,
    ammoPerBurst: null,
    basicApCost: 5,
    specialApCost: null,
    minStrength: 3,
    place: 1.5,
    weight: 1,
    value: 4500,
    frequency: 2,
    skill: "lightMedWeapons",
    knowledges: ["kFirearms", "kOneHandedWeapons"],
    tags: ["arme légère", "arme à feu", "pistolet", "explosif"]
  },
  seryngePistol: {
    id: "seryngePistol",
    label: "Pistolet à seringues",
    img: "https://vignette.wikia.nocookie.net/fallout/images/6/66/Fo2_Needler_Pistol.png/revision/latest?cb=20110427234854",
    damageType: "physical",
    damageBasic: "1D6",
    damageBurst: null,
    ammoType: "darts",
    range: 12,
    magazine: 4,
    ammoPerShot: 1,
    ammoPerBurst: null,
    basicApCost: 4,
    specialApCost: 6,
    minStrength: 2,
    place: 1,
    weight: 0.5,
    value: 150,
    frequency: 3,
    skill: "lightMedWeapons",
    knowledges: ["kOneHandedWeapons"],
    tags: ["arme légère", "pistolet", "spécial"]
  },
  incendiaryPistol: {
    id: "incendiaryPistol",
    label: "Pistolet incendiaire",
    img: "https://vignette.wikia.nocookie.net/fallout/images/d/dc/Tactics_flamer_pistol.png/revision/latest?cb=20130109142610",
    damageType: "fire",
    damageBasic: "5D6",
    damageBurst: null,
    ammoType: "gas",
    range: 3,
    magazine: 3,
    ammoPerShot: 1,
    ammoPerBurst: null,
    basicApCost: 7,
    specialApCost: null,
    minStrength: 2,
    place: 1,
    weight: 0.5,
    value: 2500,
    frequency: 2,
    skill: "lightMedWeapons",
    knowledges: ["kOneHandedWeapons"],
    tags: ["arme légère", "pistolet", "spécial"]
  },
  coltRangemaster: {
    id: "coltRangemaster",
    label: "Colt Rangemaster",
    img: "https://vignette.wikia.nocookie.net/fallout/images/1/12/HuntingRifleFoNV.png/revision/latest/scale-to-width-down/242?cb=20110207071857",
    damageType: "physical",
    damageBasic: "4D6",
    damageBurst: null,
    ammoType: "7_62mm",
    range: 180,
    magazine: 10,
    ammoPerShot: 1,
    ammoPerBurst: null,
    basicApCost: 5,
    specialApCost: 7,
    minStrength: 4,
    place: 3,
    weight: 3.5,
    value: 3000,
    frequency: 5,
    skill: "lightMedWeapons",
    knowledges: ["kTwoHandedWeapons", "kFirearms"],
    tags: ["arme moyenne", "arme à feu", "fusil"]
  },
  garandM1: {
    id: "garandM1",
    label: "M1 Garand",
    img: "https://vignette.wikia.nocookie.net/fallout/images/f/f2/Tactics_m1_garand.png/revision/latest?cb=20190716225425",
    damageType: "physical",
    damageBasic: "3D6+10",
    damageBurst: null,
    ammoType: "30_06",
    range: 180,
    magazine: 8,
    ammoPerShot: 1,
    ammoPerBurst: null,
    basicApCost: 4,
    specialApCost: 6,
    minStrength: 4,
    place: 3.5,
    weight: 4.5,
    value: 4000,
    frequency: 5,
    skill: "lightMedWeapons",
    knowledges: ["kTwoHandedWeapons", "kFirearms"],
    tags: ["arme moyenne", "arme à feu", "fusil"]
  },
  dks50: {
    id: "dks50",
    label: "Sniper DKS 50",
    img: "https://vignette.wikia.nocookie.net/fallout/images/7/78/Fo1_Sniper_Rifle.png/revision/latest?cb=20110308062208",
    damageType: "physical",
    damageBasic: "3D6+12",
    damageBurst: null,
    ammoType: "303",
    range: 800,
    magazine: 6,
    ammoPerShot: 1,
    ammoPerBurst: null,
    basicApCost: 5,
    specialApCost: 7,
    minStrength: 5,
    place: 4,
    weight: 7,
    value: 4200,
    frequency: 4,
    skill: "lightMedWeapons",
    knowledges: ["kTwoHandedWeapons", "kFirearms"],
    tags: ["arme moyenne", "arme à feu", "sniper", "fusil"]
  },
  dks70: {
    id: "dks70",
    label: "Sniper DKS 70",
    img: "https://vignette.wikia.nocookie.net/fallout/images/3/35/Sniper_rifle.png/revision/latest/scale-to-width-down/242?cb=20110206233717",
    damageType: "physical",
    damageBasic: "4D6+14",
    damageBurst: null,
    ammoType: "7_62mm",
    range: 1500,
    magazine: 6,
    ammoPerShot: 1,
    ammoPerBurst: null,
    basicApCost: 5,
    specialApCost: 7,
    minStrength: 5,
    place: 4,
    weight: 8,
    value: 4700,
    frequency: 3,
    skill: "lightMedWeapons",
    knowledges: ["kTwoHandedWeapons", "kFirearms"],
    tags: ["arme moyenne", "arme à feu", "sniper", "fusil"]
  },
  dragunov: {
    id: "dragunov",
    label: "Dragunov",
    img: "https://vignette.wikia.nocookie.net/fallout/images/8/88/Tactics_sniper_rifle.png/revision/latest?cb=20130109235506",
    damageType: "physical",
    damageBasic: "4D6+20",
    damageBurst: null,
    ammoType: "7_62mm",
    range: 800,
    magazine: 10,
    ammoPerShot: 1,
    ammoPerBurst: null,
    basicApCost: 5,
    specialApCost: 7,
    minStrength: 4,
    place: 4,
    weight: 6,
    value: 6000,
    frequency: 2,
    skill: "lightMedWeapons",
    knowledges: ["kTwoHandedWeapons", "kFirearms"],
    tags: ["arme moyenne", "arme à feu", "fusil", "sniper"]
  },
  gaussM72: {
    id: "gaussM72",
    label: "Gauss M72",
    img: "https://vignette.wikia.nocookie.net/fallout/images/1/14/Tactics_m72_Gauss_rifle.png/revision/latest?cb=20130110001910",
    damageType: "physical",
    damageBasic: "4D6+50",
    damageBurst: null,
    ammoType: "ec2mm",
    range: 500,
    magazine: 20,
    ammoPerShot: 1,
    ammoPerBurst: null,
    basicApCost: 5,
    specialApCost: 7,
    minStrength: 4,
    place: 3.5,
    weight: 3,
    value: 30000,
    frequency: 1,
    skill: "lightMedWeapons",
    knowledges: ["kTwoHandedWeapons"],
    tags: ["arme moyenne", "fusil", "spécial"]
  },
  redRyderLEBB: {
    id: "redRyderLEBB",
    label: "Red Ryder LE BB",
    img: "https://vignette.wikia.nocookie.net/fallout/images/e/e4/Fo1_Red_Ryder_LE_BB_Gun.png/revision/latest?cb=20110430014855",
    damageType: "physical",
    damageBasic: "1D6+3",
    damageBurst: null,
    ammoType: "bb",
    range: 50,
    magazine: 1,
    ammoPerShot: 1,
    ammoPerBurst: null,
    basicApCost: 4,
    specialApCost: 6,
    minStrength: 3,
    place: 3,
    weight: 3,
    value: 300,
    frequency: 5,
    skill: "lightMedWeapons",
    knowledges: ["kFirearms", "kTwoHandedWeapons"],
    tags: ["arme légère", "arme à feu", "fusil"]
  },
  redRyderSEBB: {
    id: "redRyderSEBB",
    label: "Red Ryder SE BB",
    img: "https://vignette.wikia.nocookie.net/fallout/images/0/0d/Fo1_Red_Ryder_BB_Gun.png/revision/latest?cb=20110430013825",
    damageType: "physical",
    damageBasic: "1D6+7",
    damageBurst: null,
    ammoType: "bb",
    range: 60,
    magazine: 1,
    ammoPerShot: 1,
    ammoPerBurst: null,
    basicApCost: 4,
    specialApCost: 6,
    minStrength: 3,
    place: 3,
    weight: 3,
    value: 500,
    frequency: 5,
    skill: "lightMedWeapons",
    knowledges: ["kFirearms", "kTwoHandedWeapons"],
    tags: ["arme légère", "arme à feu", "fusil"]
  },
  tromblon: {
    id: "tromblon",
    label: "Tromblon",
    img: "https://vignette.wikia.nocookie.net/fallout/images/b/bd/Tactics_zip_gun.png/revision/latest?cb=20130109144339",
    damageType: "physical",
    damageBasic: "1D6+11",
    damageBurst: null,
    ammoType: "bb",
    range: 5,
    magazine: 20,
    ammoPerShot: 20,
    ammoPerBurst: null,
    basicApCost: 5,
    specialApCost: null,
    minStrength: 3,
    place: 2,
    weight: 2.5,
    value: 750,
    frequency: 5,
    skill: "lightMedWeapons",
    knowledges: ["kFirearms", "kOneHandedWeapons"],
    tags: ["arme légère", "arme à feu"]
  },
  winchester1895: {
    id: "winchester1895",
    label: "Winchester 1895",
    img: "https://vignette.wikia.nocookie.net/fallout/images/d/d8/HuntingRifleFO3.png/revision/latest/scale-to-width-down/242?cb=20110321234637",
    damageType: "physical",
    damageBasic: "3D6+5",
    damageBurst: null,
    ammoType: "30_06",
    range: 50,
    magazine: 5,
    ammoPerShot: 1,
    ammoPerBurst: null,
    basicApCost: 5,
    specialApCost: 8,
    minStrength: 4,
    place: 3.5,
    weight: 4,
    value: 2500,
    frequency: 5,
    skill: "lightMedWeapons",
    knowledges: ["kTwoHandedWeapons", "kFirearms"],
    tags: ["arme moyenne", "arme à feu", "fusil"]
  },
  sawedShotgun: {
    id: "sawedShotgun",
    label: "Canon scié",
    img: "https://vignette.wikia.nocookie.net/fallout/images/8/89/Sawed_off.png/revision/latest/scale-to-width-down/242?cb=20110208012624",
    damageType: "physical",
    damageBasic: "4D6+4",
    damageBurst: null,
    ammoType: "12g",
    range: 15,
    magazine: 2,
    ammoPerShot: 1,
    ammoPerBurst: null,
    basicApCost: 5,
    specialApCost: null,
    minStrength: 3,
    place: 3,
    weight: 3,
    value: 2700,
    frequency: 5,
    skill: "lightMedWeapons",
    knowledges: ["kFirearms", "kOneHandedWeapons"],
    tags: ["arme légère", "arme à feu", "fusil à pompe"]
  },
  berettaSilverhawk: {
    id: "berettaSilverhawk",
    label: "Beretta Silverhawk",
    img: "https://vignette.wikia.nocookie.net/fallout/images/c/cd/Tactics_beretta_470_silverhawk.png/revision/latest?cb=20130109233536",
    damageType: "physical",
    damageBasic: "3D6+4",
    damageBurst: "5D6+6",
    ammoType: "12g",
    range: 15,
    magazine: 2,
    ammoPerShot: 1,
    ammoPerBurst: null,
    basicApCost: 5,
    specialApCost: null,
    minStrength: 3,
    place: 3,
    weight: 3,
    value: 2700,
    frequency: 4,
    skill: "lightMedWeapons",
    knowledges: ["kTwoHandedWeapons", "kFirearms"],
    tags: ["arme moyenne", "arme à feu", "fusil à pompe"]
  },
  "12gRiffle": {
    id: "12gRiffle",
    label: "Fusil cal 12",
    img: "https://vignette.wikia.nocookie.net/fallout/images/b/b9/FO76_Pump-action_shotgun.png/revision/latest/scale-to-width-down/242?cb=20200312171112",
    damageType: "physical",
    damageBasic: "4D6+6",
    damageBurst: null,
    ammoType: "12g",
    range: 50,
    magazine: 5,
    ammoPerShot: 1,
    ammoPerBurst: null,
    basicApCost: 5,
    specialApCost: 7,
    minStrength: 4,
    place: 3,
    weight: 3.5,
    value: 1800,
    frequency: 4,
    skill: "lightMedWeapons",
    knowledges: ["kTwoHandedWeapons", "kFirearms"],
    tags: ["arme moyenne", "arme à feu", "fusil à pompe"]
  },
  fmNeostead: {
    id: "fmNeostead",
    label: "FM Neostead",
    img: "https://vignette.wikia.nocookie.net/fallout/images/5/50/Tactics_neostead_combat_sg.png/revision/latest?cb=20130110003445",
    damageType: "physical",
    damageBasic: "4D6+6",
    damageBurst: null,
    ammoType: "12g",
    range: 50,
    magazine: 5,
    ammoPerShot: 1,
    ammoPerBurst: null,
    basicApCost: 4,
    specialApCost: 6,
    minStrength: 4,
    place: 2.5,
    weight: 4,
    value: 3500,
    frequency: 3,
    skill: "lightMedWeapons",
    knowledges: ["kTwoHandedWeapons", "kFirearms"],
    tags: ["arme moyenne", "arme à feu", "fusil à pompe"]
  },
  winchesterCityKiller: {
    id: "winchesterCityKiller",
    label: "Winchester City Killer",
    img: "https://vignette.wikia.nocookie.net/fallout/images/e/ee/Fo1_Combat_Shotgun.png/revision/latest?cb=20110207063715",
    damageType: "physical",
    damageBasic: "4D6+6",
    damageBurst: "5D6+10",
    ammoType: "12g",
    range: 70,
    magazine: 12,
    ammoPerShot: 1,
    ammoPerBurst: 3,
    basicApCost: 5,
    specialApCost: 7,
    minStrength: 5,
    place: 3.5,
    weight: 4,
    value: 5000,
    frequency: 3,
    skill: "lightMedWeapons",
    knowledges: ["kTwoHandedWeapons", "kFirearms"],
    tags: ["arme moyenne", "arme à feu", "fusil à pompe"]
  },
  hkCaws: {
    id: "hkCaws",
    label: "H&K Caws",
    img: "https://vignette.wikia.nocookie.net/fallout/images/d/d3/Fo2_H%26K_CAWS.png/revision/latest?cb=20110424140127",
    damageType: "physical",
    damageBasic: "4D6+6",
    damageBurst: "5D6+17",
    ammoType: "12g",
    range: 70,
    magazine: 10,
    ammoPerShot: 1,
    ammoPerBurst: 3,
    basicApCost: 5,
    specialApCost: 7,
    minStrength: 5,
    place: 3,
    weight: 4,
    value: 6500,
    frequency: 2,
    skill: "lightMedWeapons",
    knowledges: ["kTwoHandedWeapons", "kFirearms"],
    tags: ["arme moyenne", "arme à feu", "fusil à pompe"]
  },
  pancor: {
    id: "pancor",
    label: "Pancor Jackhammer",
    img: "https://vignette.wikia.nocookie.net/fallout/images/e/e7/Tactics_pancor_jackhammer.png/revision/latest?cb=20130110003921",
    damageType: "physical",
    damageBasic: "4D6+10",
    damageBurst: "5D6+25",
    ammoType: "12g",
    range: 80,
    magazine: 10,
    ammoPerShot: 1,
    ammoPerBurst: 3,
    basicApCost: 4,
    specialApCost: 6,
    minStrength: 5,
    place: 3.5,
    weight: 4.5,
    value: 8000,
    frequency: 1,
    skill: "lightMedWeapons",
    knowledges: ["kTwoHandedWeapons", "kFirearms"],
    tags: ["arme moyenne", "arme à feu", "fusil à pompe"]
  },
  calicoM950: {
    id: "calicoM950",
    label: "Calico M950",
    img: "https://vignette.wikia.nocookie.net/fallout/images/9/9a/Tactics_9mm_calico_m-950.png/revision/latest?cb=20130109141517",
    damageType: "physical",
    damageBasic: "2D6+4",
    damageBurst: "5D6+7",
    ammoType: "9mm",
    range: 150,
    magazine: 100,
    ammoPerShot: 1,
    ammoPerBurst: 5,
    basicApCost: 5,
    specialApCost: 7,
    minStrength: 4,
    place: 2.5,
    weight: 3,
    value: 2300,
    frequency: 4,
    skill: "lightMedWeapons",
    knowledges: ["kTwoHandedWeapons", "kFirearms"],
    tags: ["arme moyenne", "arme à feu", "mitrailleuse"]
  },
  calicoLiberty100: {
    id: "calicoLiberty100",
    label: "Calico Liberty 100",
    img: "https://vignette.wikia.nocookie.net/fallout/images/b/b3/Tactics_calico_liberty_100.png/revision/latest?cb=20130110125058",
    damageType: "physical",
    damageBasic: "2D6+5",
    damageBurst: "6D6+9",
    ammoType: "9mm",
    range: 150,
    magazine: 15,
    ammoPerShot: 1,
    ammoPerBurst: 5,
    basicApCost: 5,
    specialApCost: 7,
    minStrength: 4,
    place: 2,
    weight: 3,
    value: 2800,
    frequency: 3,
    skill: "lightMedWeapons",
    knowledges: ["kTwoHandedWeapons", "kFirearms"],
    tags: ["arme moyenne", "arme à feu", "mitrailleuse"]
  },
  rugerAC556f: {
    id: "rugerAC556f",
    label: "Ruger AC 556f",
    img: "https://vignette.wikia.nocookie.net/fallout/images/b/b3/Tactics_ruger_ac556f.png/revision/latest?cb=20130110130008",
    damageType: "physical",
    damageBasic: "2D6+6",
    damageBurst: "5D6+8",
    ammoType: "5_56mm",
    range: 250,
    magazine: 40,
    ammoPerShot: 1,
    ammoPerBurst: 4,
    basicApCost: 5,
    specialApCost: 7,
    minStrength: 4,
    place: 3,
    weight: 3,
    value: 2500,
    frequency: 3,
    skill: "lightMedWeapons",
    knowledges: ["kTwoHandedWeapons", "kFirearms"],
    tags: ["arme moyenne", "arme à feu", "mitrailleuse"]
  },
  mp38: {
    id: "mp38",
    label: "MP38",
    img: "https://vignette.wikia.nocookie.net/fallout/images/3/39/Tactics_mp38.png/revision/latest?cb=20130110125816",
    damageType: "physical",
    damageBasic: "2D6+7",
    damageBurst: "5D6+9",
    ammoType: "9mm",
    range: 100,
    magazine: 30,
    ammoPerShot: 1,
    ammoPerBurst: 3,
    basicApCost: 5,
    specialApCost: 7,
    minStrength: 4,
    place: 2.5,
    weight: 4.5,
    value: 3300,
    frequency: 4,
    skill: "lightMedWeapons",
    knowledges: ["kTwoHandedWeapons", "kFirearms"],
    tags: ["arme moyenne", "arme à feu", "mitrailleuse"]
  },
  mp5: {
    id: "mp5",
    label: "H&K MP5",
    img: "https://vignette.wikia.nocookie.net/fallout/images/5/53/Tactics_mp5_h%26k.png/revision/latest?cb=20130113204434",
    damageType: "physical",
    damageBasic: "2D6+7",
    damageBurst: "5D6+12",
    ammoType: "9mm",
    range: 150,
    magazine: 30,
    ammoPerShot: 1,
    ammoPerBurst: 5,
    basicApCost: 5,
    specialApCost: 7,
    minStrength: 4,
    place: 2.5,
    weight: 2.5,
    value: 5500,
    frequency: 4,
    skill: "lightMedWeapons",
    knowledges: ["kTwoHandedWeapons", "kFirearms"],
    tags: ["arme moyenne", "arme à feu", "mitrailleuse"]
  },
  greaseGun: {
    id: "greaseGun",
    label: "Mitraillette Grease Gun M3 A1",
    img: "https://vignette.wikia.nocookie.net/fallout/images/c/c5/Fo2_Grease_Gun.png/revision/latest?cb=20110307044922",
    damageType: "physical",
    damageBasic: "2D6+9",
    damageBurst: "5D6+10",
    ammoType: "45",
    range: 50,
    magazine: 30,
    ammoPerShot: 1,
    ammoPerBurst: 5,
    basicApCost: 5,
    specialApCost: 7,
    minStrength: 3,
    place: 2.5,
    weight: 3,
    value: 5000,
    frequency: 4,
    skill: "lightMedWeapons",
    knowledges: ["kTwoHandedWeapons", "kFirearms"],
    tags: ["arme moyenne", "arme à feu", "mitrailleuse"]
  },
  sten: {
    id: "sten",
    label: "Sten",
    img: "https://vignette.wikia.nocookie.net/fallout/images/c/c1/Tactics_sten_gun.png/revision/latest?cb=20140803002127",
    damageType: "physical",
    damageBasic: "2D6+8",
    damageBurst: "6D6+12",
    ammoType: "9mm",
    range: 70,
    magazine: 32,
    ammoPerShot: 1,
    ammoPerBurst: 4,
    basicApCost: 4,
    specialApCost: 6,
    minStrength: 4,
    place: 3,
    weight: 3,
    value: 5200,
    frequency: 2,
    skill: "lightMedWeapons",
    knowledges: ["kTwoHandedWeapons", "kFirearms"],
    tags: ["arme moyenne", "arme à feu", "mitrailleuse"]
  },
  thomsonM1928: {
    id: "thomsonM1928",
    label: "Thompson M 1928",
    img: "https://vignette.wikia.nocookie.net/fallout/images/7/75/Tactics_tommy_gun.png/revision/latest?cb=20130110132124",
    damageType: "physical",
    damageBasic: "2D6+11",
    damageBurst: "6D6+15",
    ammoType: "45",
    range: 100,
    magazine: 50,
    ammoPerShot: 1,
    ammoPerBurst: 5,
    basicApCost: 5,
    specialApCost: 7,
    minStrength: 5,
    place: 3.5,
    weight: 5,
    value: 8500,
    frequency: 2,
    skill: "lightMedWeapons",
    knowledges: ["kTwoHandedWeapons", "kFirearms"],
    tags: ["arme moyenne", "arme à feu", "mitrailleuse"]
  },
  m16A1: {
    id: "m16A1",
    label: "M16 A1",
    img: "https://vignette.wikia.nocookie.net/fallout/images/c/cf/Tactics_m16a1.png/revision/latest?cb=20130110001549",
    damageType: "physical",
    damageBasic: "4D6+4",
    damageBurst: "6D6+11",
    ammoType: "5_56mm",
    range: 460,
    magazine: 30,
    ammoPerShot: 1,
    ammoPerBurst: 5,
    basicApCost: 5,
    specialApCost: 7,
    minStrength: 5,
    place: 4,
    weight: 3.5,
    value: 4200,
    frequency: 3,
    skill: "lightMedWeapons",
    knowledges: ["kTwoHandedWeapons", "kFirearms"],
    tags: ["arme moyenne", "arme à feu", "fusil d'assault"]
  },
  ak47: {
    id: "ak47",
    label: "AK-47 Kalashnikov",
    img: "https://vignette.wikia.nocookie.net/fallout/images/a/a6/Tactics_ak47.png/revision/latest?cb=20130109232655",
    damageType: "physical",
    damageBasic: "4D6+6",
    damageBurst: "6D6+12",
    ammoType: "7_62mm",
    range: 350,
    magazine: 30,
    ammoPerShot: 1,
    ammoPerBurst: 5,
    basicApCost: 5,
    specialApCost: 7,
    minStrength: 5,
    place: 3.5,
    weight: 4.5,
    value: 5000,
    frequency: 2,
    skill: "lightMedWeapons",
    knowledges: ["kTwoHandedWeapons", "kFirearms"],
    tags: ["arme moyenne", "arme à feu", "fusil d'assault"]
  },
  famasG2: {
    id: "famasG2",
    label: "Famas G2",
    img: "https://image.jeuxvideo.com/medias-sm/141823/1418225399-419-artwork.png",
    damageType: "physical",
    damageBasic: "4D6+7",
    damageBurst: "6D6+14",
    ammoType: "5_56mm",
    range: 450,
    magazine: 30,
    ammoPerShot: 1,
    ammoPerBurst: 5,
    basicApCost: 5,
    specialApCost: 7,
    minStrength: 4,
    place: 3,
    weight: 4,
    value: 5700,
    frequency: 2,
    skill: "lightMedWeapons",
    knowledges: ["kTwoHandedWeapons", "kFirearms"],
    tags: ["arme moyenne", "arme à feu", "fusil d'assault"]
  },
  ak112: {
    id: "ak112",
    label: "AK-112",
    img: "https://vignette.wikia.nocookie.net/fallout/images/0/05/Fo1_assault_rifle.png/revision/latest?cb=20110207042909",
    damageType: "physical",
    damageBasic: "4D6+8",
    damageBurst: "7D6+5",
    ammoType: "5_56mm",
    range: 400,
    magazine: 30,
    ammoPerShot: 1,
    ammoPerBurst: 5,
    basicApCost: 5,
    specialApCost: 7,
    minStrength: 5,
    place: 3,
    weight: 3.5,
    value: 4000,
    frequency: 2,
    skill: "lightMedWeapons",
    knowledges: ["kTwoHandedWeapons", "kFirearms"],
    tags: ["arme moyenne", "arme à feu", "fusil d'assault"]
  },
  enfieldXL: {
    id: "enfieldXL",
    label: "Sniper Enfield XL 70 E3",
    img: "https://vignette.wikia.nocookie.net/fallout/images/3/33/Tactics_xl70e3_enfield.png/revision/latest?cb=20130109234104",
    damageType: "physical",
    damageBasic: "4D6+12",
    damageBurst: "7D6+15",
    ammoType: "5_56mm",
    range: 1500,
    magazine: 32,
    ammoPerShot: 1,
    ammoPerBurst: 8,
    basicApCost: 5,
    specialApCost: 7,
    minStrength: 5,
    place: 3.5,
    weight: 4,
    value: 7000,
    frequency: 2,
    skill: "lightMedWeapons",
    knowledges: ["kTwoHandedWeapons", "kFirearms"],
    tags: ["arme moyenne", "arme à feu", "sniper"]
  },
  garandM14: {
    id: "garandM14",
    label: "M14 Garand",
    img: "https://vignette.wikia.nocookie.net/fallout/images/d/d8/Tactics_m-14_rifle.png/revision/latest?cb=20130110001143",
    damageType: "physical",
    damageBasic: "3D6+4",
    damageBurst: "6D6+5",
    ammoType: "7_62mm",
    range: 200,
    magazine: 20,
    ammoPerShot: 1,
    ammoPerBurst: 4,
    basicApCost: 5,
    specialApCost: 7,
    minStrength: 5,
    place: 3.5,
    weight: 5,
    value: 5700,
    frequency: 3,
    skill: "lightMedWeapons",
    knowledges: ["kTwoHandedWeapons", "kFirearms"],
    tags: ["arme moyenne", "arme à feu", "fusil d'assault"]
  },
  fnFAL: {
    id: "fnFAL",
    label: "FN FAL",
    img: "https://vignette.wikia.nocookie.net/fallout/images/f/f2/Tactics_7.62_fn_fal.png/revision/latest?cb=20130109234219",
    damageType: "physical",
    damageBasic: "3D6+6",
    damageBurst: "6D6+9",
    ammoType: "7_62mm",
    range: 200,
    magazine: 20,
    ammoPerShot: 1,
    ammoPerBurst: 5,
    basicApCost: 4,
    specialApCost: 6,
    minStrength: 4,
    place: 3.5,
    weight: 4.5,
    value: 6000,
    frequency: 3,
    skill: "lightMedWeapons",
    knowledges: ["kTwoHandedWeapons", "kFirearms"],
    tags: ["arme moyenne", "arme à feu", "fusil d'assault"]
  },
  steyrAug: {
    id: "steyrAug",
    label: "Steyr Aug",
    img: "https://vignette.wikia.nocookie.net/fallout/images/4/41/Tactics_steyr.png/revision/latest?cb=20130110131420",
    damageType: "physical",
    damageBasic: "4D6+9",
    damageBurst: "6D6+9",
    ammoType: "5_56mm",
    range: 450,
    magazine: 42,
    ammoPerShot: 1,
    ammoPerBurst: 6,
    basicApCost: 4,
    specialApCost: 6,
    minStrength: 5,
    place: 3,
    weight: 4,
    value: 6000,
    frequency: 1,
    skill: "lightMedWeapons",
    knowledges: ["kTwoHandedWeapons", "kFirearms"],
    tags: ["arme moyenne", "arme à feu", "fusil d'assault"]
  },
  g36K: {
    id: "g36K",
    label: "G36K",
    img: "https://vignette.wikia.nocookie.net/fallout/images/a/a8/G3ASSAULTRIFLE.png/revision/latest/scale-to-width-down/242?cb=20110207002133",
    damageType: "physical",
    damageBasic: "4D6+10",
    damageBurst: "7D6+18",
    ammoType: "5_56mm",
    range: 500,
    magazine: 30,
    ammoPerShot: 1,
    ammoPerBurst: 6,
    basicApCost: 5,
    specialApCost: 7,
    minStrength: 5,
    place: 4,
    weight: 4,
    value: 6500,
    frequency: 1,
    skill: "lightMedWeapons",
    knowledges: ["kTwoHandedWeapons", "kFirearms"],
    tags: ["arme moyenne", "arme à feu", "fusil d'assault"]
  },
  l85A1: {
    id: "l85A1",
    label: "L85A1",
    img: "https://vignette.wikia.nocookie.net/fallout/images/e/eb/XL70E3.gif/revision/latest?cb=20090816152000",
    damageType: "physical",
    damageBasic: "4D6+12",
    damageBurst: "7D6+16",
    ammoType: "5_56mm",
    range: 400,
    magazine: 30,
    ammoPerShot: 1,
    ammoPerBurst: 6,
    basicApCost: 5,
    specialApCost: 7,
    minStrength: 5,
    place: 4,
    weight: 4,
    value: 6900,
    frequency: 1,
    skill: "lightMedWeapons",
    knowledges: ["kTwoHandedWeapons", "kFirearms"],
    tags: ["arme moyenne", "arme à feu", "fusil d'assault"]
  },
  m79: {
    id: "m79",
    label: "Lance-grenade M79",
    img: "https://vignette.wikia.nocookie.net/fallout/images/f/fc/Tactics_m79_grenade_launcher.png/revision/latest?cb=20130110003300",
    damageType: "physical",
    damageBasic: "7D6+20",
    damageBurst: null,
    ammoType: "40mm",
    range: 150,
    magazine: 1,
    ammoPerShot: 1,
    ammoPerBurst: null,
    basicApCost: 6,
    specialApCost: null,
    minStrength: 5,
    place: 2,
    weight: 2,
    value: 6500,
    frequency: 1,
    skill: "lightMedWeapons",
    knowledges: ["kTwoHandedWeapons", "kFirearms"],
    tags: ["arme moyenne", "arme à feu", "explosif", "spécial"]
  },
  bren: {
    id: "bren",
    label: "Bren",
    img: "https://vignette.wikia.nocookie.net/fallout/images/e/e6/Tactics_bren_gun.png/revision/latest?cb=20130109124643",
    damageType: "physical",
    damageBasic: null,
    damageBurst: "9D6+2",
    ammoType: "303",
    range: 180,
    magazine: 30,
    ammoPerShot: null,
    ammoPerBurst: 10,
    basicApCost: null,
    specialApCost: null,
    minStrength: 6,
    place: 4.5,
    weight: 8.5,
    value: 7000,
    frequency: 2,
    skill: "heavyWeapons",
    knowledges: ["kTwoHandedWeapons", "kFirearms"],
    tags: ["arme lourde", "arme à feu", "mitrailleuse lourde"]
  },
  lewisMkII: {
    id: "lewisMkII",
    label: "Lewis Mk II",
    img: "https://vignette.wikia.nocookie.net/fallout/images/e/e1/Tactics_lewis_mkii.png/revision/latest?cb=20130109124846",
    damageType: "physical",
    damageBasic: null,
    damageBurst: "8D6+7",
    ammoType: "303",
    range: 200,
    magazine: 50,
    ammoPerShot: null,
    ammoPerBurst: 10,
    basicApCost: null,
    specialApCost: null,
    minStrength: 7,
    place: 5,
    weight: 12,
    value: 7000,
    frequency: 2,
    skill: "heavyWeapons",
    knowledges: ["kTwoHandedWeapons", "kFirearms"],
    tags: ["arme lourde", "arme à feu", "mitrailleuse lourde"]
  },
  m60: {
    id: "m60",
    label: "M-60",
    img: "https://vignette.wikia.nocookie.net/fallout/images/d/dc/Tactics_m60.png/revision/latest?cb=20130109125000",
    damageType: "physical",
    damageBasic: null,
    damageBurst: "8D6+15",
    ammoType: "7_62mm",
    range: 250,
    magazine: 100,
    ammoPerShot: null,
    ammoPerBurst: 10,
    basicApCost: null,
    specialApCost: null,
    minStrength: 7,
    place: 4.5,
    weight: 10,
    value: 8500,
    frequency: 2,
    skill: "heavyWeapons",
    knowledges: ["kTwoHandedWeapons", "kFirearms"],
    tags: ["arme lourde", "arme à feu", "mitrailleuse lourde"]
  },
  m249: {
    id: "m249",
    label: "M249",
    img: "https://vignette.wikia.nocookie.net/fallout/images/e/e8/Tactics_m249_saw.png/revision/latest?cb=20130109125433",
    damageType: "physical",
    damageBasic: null,
    damageBurst: "9D6+12",
    ammoType: "7_62mm",
    range: 200,
    magazine: 50,
    ammoPerShot: null,
    ammoPerBurst: 10,
    basicApCost: null,
    specialApCost: null,
    minStrength: 7,
    place: 4.5,
    weight: 10,
    value: 8500,
    frequency: 2,
    skill: "heavyWeapons",
    knowledges: ["kTwoHandedWeapons", "kFirearms"],
    tags: ["arme lourde", "arme à feu", "mitrailleuse lourde"]
  },
  browningM2: {
    id: "browningM2",
    label: "Browning M2",
    img: "https://vignette.wikia.nocookie.net/fallout/images/e/ea/Tactics_browning_m2.png/revision/latest?cb=20130109135842",
    damageType: "physical",
    damageBasic: null,
    damageBurst: "8D6+30",
    ammoType: "50",
    range: 200,
    magazine: 100,
    ammoPerShot: null,
    ammoPerBurst: 10,
    basicApCost: null,
    specialApCost: null,
    minStrength: 9,
    place: 7,
    weight: 38,
    value: 13000,
    frequency: 1,
    skill: "heavyWeapons",
    knowledges: ["kTwoHandedWeapons", "kFirearms"],
    tags: ["arme lourde", "arme à feu", "mitrailleuse lourde"]
  },
  CZ4000: {
    id: "CZ4000",
    label: "Rockwell CZ4000",
    img: "https://vignette.wikia.nocookie.net/fallout/images/3/3b/Fo1_Minigun.png/revision/latest?cb=20110427230356",
    damageType: "physical",
    damageBasic: null,
    damageBurst: "10D6+9",
    ammoType: "5_56mm",
    range: 100,
    magazine: 120,
    ammoPerShot: null,
    ammoPerBurst: 30,
    basicApCost: null,
    specialApCost: null,
    minStrength: 7,
    place: 5,
    weight: 14,
    value: 8500,
    frequency: 2,
    skill: "heavyWeapons",
    knowledges: ["kTwoHandedWeapons", "kFirearms"],
    tags: ["arme lourde", "arme à feu", "minigun"]
  },
  avenger: {
    id: "avenger",
    label: "Avenger",
    img: "https://vignette.wikia.nocookie.net/fallout/images/2/2c/Tactics_avenger_minigun.png/revision/latest?cb=20130127201841",
    damageType: "physical",
    damageBasic: null,
    damageBurst: "10D6+15",
    ammoType: "5_56mm",
    range: 150,
    magazine: 120,
    ammoPerShot: null,
    ammoPerBurst: 30,
    basicApCost: null,
    specialApCost: null,
    minStrength: 8,
    place: 5,
    weight: 18,
    value: 9500,
    frequency: 2,
    skill: "heavyWeapons",
    knowledges: ["kTwoHandedWeapons", "kFirearms"],
    tags: ["arme lourde", "arme à feu", "minigun"]
  },
  vindicator: {
    id: "vindicator",
    label: "Rheinmetal AG Vindicator",
    img: "https://vignette.wikia.nocookie.net/fallout/images/f/fb/Tactics_vindicator_minigun.png/revision/latest?cb=20130109135803",
    damageType: "physical",
    damageBasic: null,
    damageBurst: "10D6+30",
    ammoType: "5_56mm",
    range: 180,
    magazine: 120,
    ammoPerShot: null,
    ammoPerBurst: 40,
    basicApCost: null,
    specialApCost: null,
    minStrength: 8,
    place: 5,
    weight: 16,
    value: 11000,
    frequency: 1,
    skill: "heavyWeapons",
    knowledges: ["kTwoHandedWeapons", "kFirearms"],
    tags: ["arme lourde", "arme à feu", "minigun"]
  },
  gaussMinigun: {
    id: "gaussMinigun",
    label: "Minigun Gauss",
    img: "https://vignette.wikia.nocookie.net/fallout/images/5/50/Tactics_mec_gauss_minigun.png/revision/latest?cb=20130109135818",
    damageType: "physical",
    damageBasic: null,
    damageBurst: "10D6+50",
    ammoType: "ec2mm",
    range: 150,
    magazine: 800,
    ammoPerShot: null,
    ammoPerBurst: 200,
    basicApCost: null,
    specialApCost: null,
    minStrength: 6,
    place: 4.5,
    weight: 7,
    value: 50000,
    frequency: 1,
    skill: "heavyWeapons",
    knowledges: ["kTwoHandedWeapons"],
    tags: ["arme lourde", "spécial", "minigun"]
  },
  bazooka: {
    id: "bazooka",
    label: "Rockwell Bazooka",
    img: "https://vignette.wikia.nocookie.net/fallout/images/2/26/Tactics_rocket_launcher.png/revision/latest?cb=20100919162040",
    damageType: "physical",
    damageBasic: "3D20+40",
    damageBurst: null,
    ammoType: "missile",
    range: 180,
    magazine: 1,
    ammoPerShot: 1,
    ammoPerBurst: null,
    basicApCost: 7,
    specialApCost: null,
    minStrength: 6,
    place: 4,
    weight: 10,
    value: 12000,
    frequency: 2,
    skill: "heavyWeapons",
    knowledges: ["kTwoHandedWeapons"],
    tags: ["arme lourde", "spécial", "explosif"]
  },
  m224: {
    id: "m224",
    label: "Mortier M224",
    img: "https://vignette.wikia.nocookie.net/fallout/images/5/5d/Mortar_%28Fallout_4%29.png/revision/latest/scale-to-width-down/242?cb=20151115045505",
    damageType: "physical",
    damageBasic: "8D6+45",
    damageBurst: null,
    ammoType: "shell60mm",
    range: 2500,
    magazine: 1,
    ammoPerShot: 1,
    ammoPerBurst: null,
    basicApCost: 8,
    specialApCost: null,
    minStrength: 1,
    place: 8,
    weight: 61,
    value: 10000,
    frequency: 2,
    skill: "heavyWeapons",
    knowledges: ["kTwoHandedWeapons"],
    tags: ["arme lourde", "spécial", "explosif"]
  },
  alienBlaster: {
    id: "alienBlaster",
    label: "Alien Blaster",
    img: "https://vignette.wikia.nocookie.net/fallout/images/a/a5/Fo1_alien_blaster.png/revision/latest?cb=20110502054300",
    damageType: "other",
    damageBasic: "10D6+30",
    damageBurst: null,
    ammoType: "special",
    range: 100,
    magazine: 30,
    ammoPerShot: 1,
    ammoPerBurst: null,
    basicApCost: 3,
    specialApCost: 5,
    minStrength: 2,
    place: 0.5,
    weight: 0.5,
    value: 100000,
    frequency: 1,
    skill: "lightMedWeapons",
    knowledges: ["kEnergyWeapons"],
    tags: ["arme légère", "pistolet", "arme à énergie"]
  },
  glock86Plasma: {
    id: "glock86Plasma",
    label: "Glock 86 Plasma",
    img: "https://vignette.wikia.nocookie.net/fallout/images/f/f8/Tactics_laser_pistol.png/revision/latest?cb=20130109142756",
    damageType: "plasma",
    damageBasic: "4D6+10",
    damageBurst: null,
    ammoType: "energyCell",
    range: 80,
    magazine: 16,
    ammoPerShot: 1,
    ammoPerBurst: null,
    basicApCost: 5,
    specialApCost: 7,
    minStrength: 2,
    place: 1,
    weight: 0.5,
    value: 6000,
    frequency: 2,
    skill: "lightMedWeapons",
    knowledges: ["kEnergyWeapons", "kOneHandedWeapons"],
    tags: ["arme légère", "pistolet", "arme à énergie"]
  },
  glock96Plasma: {
    id: "glock96Plasma",
    label: "Glock 96 Plasma",
    img: "https://vignette.wikia.nocookie.net/fallout/images/0/0d/Tactics_plasma_pistol.png/revision/latest?cb=20130109143508",
    damageType: "plasma",
    damageBasic: "4D6+15",
    damageBurst: null,
    ammoType: "energyCell",
    range: 100,
    magazine: 32,
    ammoPerShot: 1,
    ammoPerBurst: null,
    basicApCost: 5,
    specialApCost: 7,
    minStrength: 2,
    place: 1,
    weight: 0.5,
    value: 7000,
    frequency: 2,
    skill: "lightMedWeapons",
    knowledges: ["kEnergyWeapons", "kOneHandedWeapons"],
    tags: ["arme légère", "pistolet", "arme à énergie"]
  },
  wattz1000: {
    id: "wattz1000",
    label: "Wattz 1000 Laser",
    img: "https://vignette.wikia.nocookie.net/fallout/images/a/af/Fo1_Laser_Pistol.png/revision/latest?cb=20110308172257",
    damageType: "laser",
    damageBasic: "2D6+9",
    damageBurst: null,
    ammoType: "energyCell",
    range: 150,
    magazine: 12,
    ammoPerShot: 1,
    ammoPerBurst: null,
    basicApCost: 4,
    specialApCost: 6,
    minStrength: 2,
    place: 1,
    weight: 1,
    value: 3500,
    frequency: 2,
    skill: "lightMedWeapons",
    knowledges: ["kEnergyWeapons", "kOneHandedWeapons"],
    tags: ["arme légère", "pistolet", "arme à énergie"]
  },
  wattz1600: {
    id: "wattz1600",
    label: "Wattz 1600 Laser",
    img: "https://vignette.wikia.nocookie.net/fallout/images/c/cb/Fo2_Magneto-Laser_Pistol.png/revision/latest?cb=20110308173636",
    damageType: "laser",
    damageBasic: "2D6+15",
    damageBurst: null,
    ammoType: "energyCell",
    range: 150,
    magazine: 24,
    ammoPerShot: 1,
    ammoPerBurst: null,
    basicApCost: 4,
    specialApCost: 6,
    minStrength: 2,
    place: 1,
    weight: 1,
    value: 4750,
    frequency: 2,
    skill: "lightMedWeapons",
    knowledges: ["kFirearms", "kEnergyWeapons", "kOneHandedWeapons"],
    tags: ["arme légère", "arme à feu", "arme à énergie"]
  },
  solarScorcher: {
    id: "solarScorcher",
    label: "Lance-flammes Solaire",
    img: "https://vignette.wikia.nocookie.net/fallout/images/c/cd/Fo2_Solar_Scorcher.png/revision/latest?cb=20110430090730",
    damageType: "fire",
    damageBasic: "8D6+38",
    damageBurst: null,
    ammoType: "microFusion",
    range: 30,
    magazine: 1,
    ammoPerShot: 1,
    ammoPerBurst: null,
    basicApCost: 5,
    specialApCost: null,
    minStrength: 3,
    place: 2.5,
    weight: 2,
    value: 10000,
    frequency: 1,
    skill: "lightMedWeapons",
    knowledges: ["kTwoHandedWeapons", "kEnergyWeapons"],
    tags: ["arme moyenne", "spécial", "arme à énergie"]
  },
  yk32: {
    id: "yk32",
    label: "Pistolet YK 32",
    img: "https://vignette.wikia.nocookie.net/fallout/images/a/a3/Tactics_yk32_pulse_pistol.png/revision/latest?cb=20130109143907",
    damageType: "other",
    damageBasic: "4D6+25",
    damageBurst: null,
    ammoType: "energyCell",
    range: 30,
    magazine: 5,
    ammoPerShot: 1,
    ammoPerBurst: null,
    basicApCost: 4,
    specialApCost: 6,
    minStrength: 2,
    place: 1,
    weight: 1,
    value: 12500,
    frequency: 1,
    skill: "lightMedWeapons",
    knowledges: ["kFirearms", "kEnergyWeapons", "kOneHandedWeapons"],
    tags: ["arme légère", "arme à feu", "arme à énergie"]
  },
  p94: {
    id: "p94",
    label: "Fusil à Plasma P94",
    img: "https://vignette.wikia.nocookie.net/fallout/images/e/ef/Fo1_plasma_rifle.png/revision/latest?cb=20110428003121",
    damageType: "plasma",
    damageBasic: "8D6+12",
    damageBurst: null,
    ammoType: "microFusion",
    range: 150,
    magazine: 10,
    ammoPerShot: 1,
    ammoPerBurst: null,
    basicApCost: 5,
    specialApCost: 7,
    minStrength: 5,
    place: 4,
    weight: 5,
    value: 16000,
    frequency: 1,
    skill: "lightMedWeapons",
    knowledges: ["kTwoHandedWeapons", "kEnergyWeapons"],
    tags: ["arme moyenne", "fusil", "arme à énergie"]
  },
  p96: {
    id: "p96",
    label: "Fusil à Plasma P96",
    img: "https://vignette.wikia.nocookie.net/fallout/images/b/bc/Fo1_turbo_plasma_rifle.png/revision/latest?cb=20110428000509",
    damageType: "plasma",
    damageBasic: "8D6+20",
    damageBurst: null,
    ammoType: "microFusion",
    range: 150,
    magazine: 20,
    ammoPerShot: 1,
    ammoPerBurst: null,
    basicApCost: 5,
    specialApCost: 7,
    minStrength: 5,
    place: 4,
    weight: 6,
    value: 18000,
    frequency: 1,
    skill: "lightMedWeapons",
    knowledges: ["kTwoHandedWeapons", "kEnergyWeapons"],
    tags: ["arme moyenne", "fusil", "arme à énergie"]
  },
  iemRiffle: {
    id: "iemRiffle",
    label: "Prototype de  IEM",
    img: "https://vignette.wikia.nocookie.net/fallout/images/c/c7/Tactics_pulse_rifle_prototype.png/revision/latest?cb=20130110004605",
    damageType: "other",
    damageBasic: "6D6+40",
    damageBurst: null,
    ammoType: "microFusion",
    range: 100,
    magazine: 8,
    ammoPerShot: 1,
    ammoPerBurst: null,
    basicApCost: 4,
    specialApCost: 6,
    minStrength: 4,
    place: 3,
    weight: 3.5,
    value: 25000,
    frequency: 1,
    skill: "lightMedWeapons",
    knowledges: ["kTwoHandedWeapons", "kEnergyWeapons"],
    tags: ["arme moyenne", "fusil", "arme à énergie"]
  },
  iemYK42B: {
    id: "iemYK42B",
    label: "Fusil IEM YK 42b",
    img: "https://vignette.wikia.nocookie.net/fallout/images/a/a0/Fo2_YK42B_Pulse_Rifle.png/revision/latest?cb=20120414231738",
    damageType: "other",
    damageBasic: "8D6+50",
    damageBurst: null,
    ammoType: "microFusion",
    range: 150,
    magazine: 10,
    ammoPerShot: 1,
    ammoPerBurst: null,
    basicApCost: 5,
    specialApCost: 7,
    minStrength: 4,
    place: 3,
    weight: 3.5,
    value: 45000,
    frequency: 1,
    skill: "lightMedWeapons",
    knowledges: ["kTwoHandedWeapons", "kEnergyWeapons"],
    tags: ["arme moyenne", "fusil", "arme à énergie"]
  },
  wattz2000: {
    id: "wattz2000",
    label: "Wattz 2000 Sniper Laser",
    img: "https://vignette.wikia.nocookie.net/fallout/images/8/8a/Fo1_laser_rifle.png/revision/latest?cb=20110308062908",
    damageType: "laser",
    damageBasic: "4D6+20",
    damageBurst: null,
    ammoType: "microFusion",
    range: 1500,
    magazine: 12,
    ammoPerShot: 1,
    ammoPerBurst: null,
    basicApCost: 5,
    specialApCost: 7,
    minStrength: 5,
    place: 4,
    weight: 5,
    value: 9000,
    frequency: 2,
    skill: "lightMedWeapons",
    knowledges: ["kTwoHandedWeapons", "kEnergyWeapons"],
    tags: ["sniper", "arme moyenne", "fusil", "arme à énergie"]
  },
  gatlingLaser: {
    id: "gatlingLaser",
    label: "Gatling Laser",
    img: "https://vignette.wikia.nocookie.net/fallout/images/3/3b/Fo1_Gatling_Laser.png/revision/latest?cb=20110308165928",
    damageType: "laser",
    damageBasic: null,
    damageBurst: "10D6+32",
    ammoType: "microFusion",
    range: 200,
    magazine: 30,
    ammoPerShot: null,
    ammoPerBurst: 5,
    basicApCost: null,
    specialApCost: 7,
    minStrength: 6,
    place: 4.5,
    weight: 8,
    value: 14000,
    frequency: 1,
    skill: "heavyWeapons",
    knowledges: ["kTwoHandedWeapons", "kEnergyWeapons"],
    tags: ["arme lourde", "minigun", "arme à énergie"]
  },
  flamer450: {
    id: "flamer450",
    label: "Flambe's 450",
    img: "https://vignette.wikia.nocookie.net/fallout/images/9/9d/Fo1_Flamer.png/revision/latest?cb=20110207044241",
    damageType: "fire",
    damageBasic: null,
    damageBurst: "7D6+20",
    ammoType: "gas",
    range: 12,
    magazine: 3,
    ammoPerShot: null,
    ammoPerBurst: 1,
    basicApCost: null,
    specialApCost: 7,
    minStrength: 7,
    place: 5,
    weight: 8,
    value: 6000,
    frequency: 2,
    skill: "heavyWeapons",
    knowledges: ["kTwoHandedWeapons"],
    tags: ["arme lourde", "spécial"]
  },
  flamer450MKII: {
    id: "flamer450MKII",
    label: "Flambe's 450 MK II",
    img: "https://vignette.wikia.nocookie.net/fallout/images/b/b1/Tactics_flamer.png/revision/latest?cb=20130109124751",
    damageType: "fire",
    damageBasic: null,
    damageBurst: "8D6+25",
    ammoType: "gas",
    range: 20,
    magazine: 6,
    ammoPerShot: null,
    ammoPerBurst: 1,
    basicApCost: null,
    specialApCost: 7,
    minStrength: 7,
    place: 5,
    weight: 8,
    value: 7500,
    frequency: 1,
    skill: "heavyWeapons",
    knowledges: ["kTwoHandedWeapons"],
    tags: ["arme lourde", "spécial"]
  },
  bowingGloves: {
    id: "bowingGloves",
    label: "Gants de boxe",
    img: "https://vignette.wikia.nocookie.net/fallout/images/9/95/Fo2_Boxing_Gloves.png/revision/latest?cb=20110307002426",
    damageType: "physical",
    damageBasic: "1D6+DM+1",
    damageBurst: null,
    ammoType: null,
    range: null,
    magazine: null,
    ammoPerShot: null,
    ammoPerBurst: null,
    basicApCost: 3,
    specialApCost: 5,
    minStrength: 3,
    place: 1,
    weight: 0.5,
    value: 50,
    frequency: 5,
    skill: "unarmed",
    knowledges: ["kUnarmed"],
    tags: ["arme de corps à corps"]
  },
  brassKnuckles: {
    id: "brassKnuckles",
    label: "Poing Américain",
    img: "https://vignette.wikia.nocookie.net/fallout/images/9/92/Fo1_brass_knuckles.png/revision/latest?cb=20110207044446",
    damageType: "physical",
    damageBasic: "1D6+DM+2",
    damageBurst: null,
    ammoType: null,
    range: null,
    magazine: null,
    ammoPerShot: null,
    ammoPerBurst: null,
    basicApCost: 3,
    specialApCost: 5,
    minStrength: 3,
    place: 0.5,
    weight: 0.1,
    value: 60,
    frequency: 5,
    skill: "unarmed",
    knowledges: ["kUnarmed"],
    tags: ["arme de corps à corps"]
  },
  spikedKnuckles: {
    id: "spikedKnuckles",
    label: "Poing Américain aiguisé",
    img: "https://vignette.wikia.nocookie.net/fallout/images/2/27/Fo1_spiked_knuckles.png/revision/latest?cb=20110207043712",
    damageType: "physical",
    damageBasic: "1D6+DM+3",
    damageBurst: null,
    ammoType: null,
    range: null,
    magazine: null,
    ammoPerShot: null,
    ammoPerBurst: null,
    basicApCost: 3,
    specialApCost: 5,
    minStrength: 3,
    place: 0.5,
    weight: 0.2,
    value: 75,
    frequency: 4,
    skill: "unarmed",
    knowledges: ["kUnarmed"],
    tags: ["arme de corps à corps"]
  },
  sappers: {
    id: "sappers",
    label: "Cogneur",
    img: "https://vignette.wikia.nocookie.net/fallout/images/1/19/Tactics_sappers.png/revision/latest?cb=20130111013641",
    damageType: "physical",
    damageBasic: "1D6+DM+4",
    damageBurst: null,
    ammoType: null,
    range: null,
    magazine: null,
    ammoPerShot: null,
    ammoPerBurst: null,
    basicApCost: 3,
    specialApCost: 5,
    minStrength: 3,
    place: 1,
    weight: 0.5,
    value: 90,
    frequency: 4,
    skill: "unarmed",
    knowledges: ["kUnarmed"],
    tags: ["arme de corps à corps"]
  },
  lacerator: {
    id: "lacerator",
    label: "Lacéreurs",
    img: "https://vignette.wikia.nocookie.net/fallout/images/a/ab/Tactics_lacerators.png/revision/latest?cb=20130111013033",
    damageType: "physical",
    damageBasic: "1D6+DM+5",
    damageBurst: null,
    ammoType: null,
    range: null,
    magazine: null,
    ammoPerShot: null,
    ammoPerBurst: null,
    basicApCost: 3,
    specialApCost: 5,
    minStrength: 3,
    place: 1.5,
    weight: 1,
    value: 200,
    frequency: 4,
    skill: "unarmed",
    knowledges: ["kUnarmed"],
    tags: ["arme de corps à corps"]
  },
  maceGlove: {
    id: "maceGlove",
    label: "Gant Masse",
    img: "https://vignette.wikia.nocookie.net/fallout/images/2/21/Tactics_mace_glove.png/revision/latest?cb=20130111012030",
    damageType: "physical",
    damageBasic: "1D6+DM+7",
    damageBurst: null,
    ammoType: null,
    range: null,
    magazine: null,
    ammoPerShot: null,
    ammoPerBurst: null,
    basicApCost: 4,
    specialApCost: 6,
    minStrength: 3,
    place: 1,
    weight: 1,
    value: 400,
    frequency: 4,
    skill: "unarmed",
    knowledges: ["kUnarmed"],
    tags: ["arme de corps à corps"]
  },
  razorClaws: {
    id: "razorClaws",
    label: "Lames Adamantines",
    img: "https://vignette.wikia.nocookie.net/fallout/images/b/b8/Tactics_razor_claws.png/revision/latest?cb=20130111015317",
    damageType: "physical",
    damageBasic: "1D6+DM+10",
    damageBurst: null,
    ammoType: null,
    range: null,
    magazine: null,
    ammoPerShot: null,
    ammoPerBurst: null,
    basicApCost: 3,
    specialApCost: 5,
    minStrength: 3,
    place: 1,
    weight: 0.5,
    value: 2000,
    frequency: 3,
    skill: "unarmed",
    knowledges: ["kUnarmed"],
    tags: ["arme de corps à corps"]
  },
  powerFist: {
    id: "powerFist",
    label: "Poing Energétique",
    img: "https://vignette.wikia.nocookie.net/fallout/images/f/f1/Fo1_power_fist.png/revision/latest?cb=20110207071344",
    damageType: "physical",
    damageBasic: "3D6+DM+15",
    damageBurst: null,
    ammoType: "energyCell",
    range: null,
    magazine: 5,
    ammoPerShot: 1,
    ammoPerBurst: null,
    basicApCost: 4,
    specialApCost: 6,
    minStrength: 4,
    place: 1,
    weight: 1,
    value: 4000,
    frequency: 1,
    skill: "unarmed",
    knowledges: ["kUnarmed", "kEnergyWeapons"],
    tags: ["arme de corps à corps", "arme à énergie"]
  },
  megaPowerFist: {
    id: "megaPowerFist",
    label: "Méga Super Point Energétique",
    img: "https://vignette.wikia.nocookie.net/fallout/images/5/5a/Fo2_Mega_power_fist.png/revision/latest?cb=20110207072126",
    damageType: "physical",
    damageBasic: "3D6+DM+30",
    damageBurst: null,
    ammoType: "energyCell",
    range: null,
    magazine: 5,
    ammoPerShot: 1,
    ammoPerBurst: null,
    basicApCost: 4,
    specialApCost: 6,
    minStrength: 5,
    place: 1,
    weight: 1,
    value: 8000,
    frequency: 1,
    skill: "unarmed",
    knowledges: ["kUnarmed", "kEnergyWeapons"],
    tags: ["arme de corps à corps", "arme à énergie"]
  },
  cattleStick: {
    id: "cattleStick",
    label: "Aiguillon à bétail",
    img: "https://vignette.wikia.nocookie.net/fallout/images/d/d7/Tactics_cattle_prod.png/revision/latest?cb=20130109134108",
    damageType: "other",
    damageBasic: "1D6+DM+2",
    damageBurst: null,
    ammoType: "energyCell",
    range: null,
    magazine: 500,
    ammoPerShot: 1,
    ammoPerBurst: null,
    basicApCost: 4,
    specialApCost: 6,
    minStrength: 3,
    place: 2,
    weight: 2,
    value: 100,
    frequency: 4,
    skill: "blunt",
    knowledges: ["kTwoHandedWeapons", "kEnergyWeapons", "kBluntWeapons"],
    tags: ["arme moyenne", "arme blanche", "arme à énergie"]
  },
  sharpenedPole: {
    id: "sharpenedPole",
    label: "Bâton",
    img: "https://vignette.wikia.nocookie.net/fallout/images/6/6b/Tactics_sharpened_pole.png/revision/latest?cb=20130110134752",
    damageType: "physical",
    damageBasic: "1D6+DM+3",
    damageBurst: null,
    ammoType: null,
    range: null,
    magazine: null,
    ammoPerShot: null,
    ammoPerBurst: null,
    basicApCost: 4,
    specialApCost: 6,
    minStrength: 3,
    place: 2,
    weight: 1,
    value: 20,
    frequency: 5,
    skill: "blunt",
    knowledges: ["kTwoHandedWeapons", "kBladedWeapons"],
    tags: ["arme moyenne", "arme blanche"]
  },
  scalpel: {
    id: "scalpel",
    label: "Scalpel",
    img: "https://vignette.wikia.nocookie.net/fallout/images/9/94/Tactics_scalpel.png/revision/latest?cb=20130109002742",
    damageType: "physical",
    damageBasic: "1D6+DM+3",
    damageBurst: null,
    ammoType: null,
    range: null,
    magazine: null,
    ammoPerShot: null,
    ammoPerBurst: null,
    basicApCost: 4,
    specialApCost: 6,
    minStrength: 2,
    place: 0.5,
    weight: 0.1,
    value: 25,
    frequency: 5,
    skill: "blunt",
    knowledges: ["kBladedWeapons", "kOneHandedWeapons"],
    tags: ["arme légère", "arme blanche"]
  },
  club: {
    id: "club",
    label: "Matraque",
    img: "https://vignette.wikia.nocookie.net/fallout/images/4/4a/Fo1_Club.png/revision/latest?cb=20110207063203",
    damageType: "physical",
    damageBasic: "1D6+DM+5",
    damageBurst: null,
    ammoType: null,
    range: null,
    magazine: null,
    ammoPerShot: null,
    ammoPerBurst: null,
    basicApCost: 4,
    specialApCost: 6,
    minStrength: 3,
    place: 1,
    weight: 1,
    value: 75,
    frequency: 5,
    skill: "blunt",
    knowledges: ["kTwoHandedWeapons", "kBluntWeapons"],
    tags: ["arme moyenne", "arme blanche"]
  },
  baseball: {
    id: "baseball",
    label: "Batte de baseball",
    img: "https://vignette.wikia.nocookie.net/fallout/images/6/6f/Tactics_slugger.png/revision/latest?cb=20130109134050",
    damageType: "physical",
    damageBasic: "2D6+DM",
    damageBurst: null,
    ammoType: null,
    range: null,
    magazine: null,
    ammoPerShot: null,
    ammoPerBurst: null,
    basicApCost: 4,
    specialApCost: 6,
    minStrength: 3,
    place: 2,
    weight: 2,
    value: 50,
    frequency: 5,
    skill: "blunt",
    knowledges: ["kTwoHandedWeapons", "kBluntWeapons"],
    tags: ["arme moyenne", "arme blanche"]
  },
  spear: {
    id: "spear",
    label: "Lance",
    img: "https://vignette.wikia.nocookie.net/fallout/images/f/f2/Tactics_spear.png/revision/latest?cb=20130110135401",
    damageType: "physical",
    damageBasic: "2D6+DM",
    damageBurst: null,
    ammoType: null,
    range: null,
    magazine: null,
    ammoPerShot: null,
    ammoPerBurst: null,
    basicApCost: 4,
    specialApCost: 6,
    minStrength: 4,
    place: 3,
    weight: 3,
    value: 20,
    frequency: 4,
    skill: "blunt",
    knowledges: ["kTwoHandedWeapons", "kBladedWeapons"],
    tags: ["arme moyenne", "arme blanche"]
  },
  wrench: {
    id: "wrench",
    label: "Clé anglaise",
    img: "https://vignette.wikia.nocookie.net/fallout/images/8/8d/Tactics_rusty_old_monkey_wrench.png/revision/latest?cb=20121223215905",
    damageType: "physical",
    damageBasic: "2D6+DM+2",
    damageBurst: null,
    ammoType: null,
    range: null,
    magazine: null,
    ammoPerShot: null,
    ammoPerBurst: null,
    basicApCost: 4,
    specialApCost: 6,
    minStrength: 3,
    place: 1,
    weight: 1,
    value: 50,
    frequency: 5,
    skill: "blunt",
    knowledges: ["kTwoHandedWeapons", "kBluntWeapons"],
    tags: ["arme lourde", "arme blanche"]
  },
  crowbar: {
    id: "crowbar",
    label: "Pied de biche",
    img: "https://vignette.wikia.nocookie.net/fallout/images/2/28/Tactics_crowbar.png/revision/latest?cb=20130109134156",
    damageType: "physical",
    damageBasic: "2D6+DM+2",
    damageBurst: null,
    ammoType: null,
    range: null,
    magazine: null,
    ammoPerShot: null,
    ammoPerBurst: null,
    basicApCost: 4,
    specialApCost: 6,
    minStrength: 3,
    place: 1.5,
    weight: 1,
    value: 45,
    frequency: 5,
    skill: "blunt",
    knowledges: ["kTwoHandedWeapons", "kBluntWeapons"],
    tags: ["arme moyenne", "arme blanche"]
  },
  knife: {
    id: "knife",
    label: "Couteau",
    img: "https://vignette.wikia.nocookie.net/fallout/images/b/b0/Fo1_Knife.png/revision/latest?cb=20110427235229",
    damageType: "physical",
    damageBasic: "2D6+DM+1",
    damageBurst: null,
    ammoType: null,
    range: null,
    magazine: null,
    ammoPerShot: null,
    ammoPerBurst: null,
    basicApCost: 4,
    specialApCost: 6,
    minStrength: 3,
    place: 0.5,
    weight: 0.2,
    value: 60,
    frequency: 5,
    skill: "blunt",
    knowledges: ["kBladedWeapons", "kOneHandedWeapons"],
    tags: ["arme légère", "arme blanche"]
  },
  combatKnife: {
    id: "combatKnife",
    label: "Couteau de combat",
    img: "https://vignette.wikia.nocookie.net/fallout/images/c/c7/Fo1_combat_knife.png/revision/latest?cb=20110307003130",
    damageType: "physical",
    damageBasic: "2D6+DM+3",
    damageBurst: null,
    ammoType: null,
    range: null,
    magazine: null,
    ammoPerShot: null,
    ammoPerBurst: null,
    basicApCost: 4,
    specialApCost: 6,
    minStrength: 3,
    place: 0.5,
    weight: 0.3,
    value: 120,
    frequency: 4,
    skill: "blunt",
    knowledges: ["kBladedWeapons", "kOneHandedWeapons"],
    tags: ["arme légère", "arme blanche"]
  },
  cleaver: {
    id: "cleaver",
    label: "Couperet",
    img: "https://vignette.wikia.nocookie.net/fallout/images/7/74/Tactics_cleaver.png/revision/latest?cb=20130109001853",
    damageType: "physical",
    damageBasic: "2D6+DM+6",
    damageBurst: null,
    ammoType: null,
    range: null,
    magazine: null,
    ammoPerShot: null,
    ammoPerBurst: null,
    basicApCost: 4,
    specialApCost: 6,
    minStrength: 3,
    place: 1,
    weight: 0.5,
    value: 80,
    frequency: 5,
    skill: "blunt",
    knowledges: ["kBladedWeapons", "kOneHandedWeapons"],
    tags: ["arme légère", "arme blanche"]
  },
  sword: {
    id: "sword",
    label: "Epée",
    img: "https://vignette.wikia.nocookie.net/fallout/images/8/82/Chinese_officer%27s_sword.png/revision/latest/scale-to-width-down/242?cb=20110211050224",
    damageType: "physical",
    damageBasic: "3D6+DM",
    damageBurst: null,
    ammoType: null,
    range: null,
    magazine: null,
    ammoPerShot: null,
    ammoPerBurst: null,
    basicApCost: 4,
    specialApCost: 6,
    minStrength: 4,
    place: 2,
    weight: 4,
    value: 400,
    frequency: 3,
    skill: "blunt",
    knowledges: ["kBladedWeapons", "kOneHandedWeapons"],
    tags: ["arme moyenne", "arme blanche"]
  },
  hammer: {
    id: "hammer",
    label: "Marteau",
    img: "https://vignette.wikia.nocookie.net/fallout/images/4/49/Tactics_claw_hammer.png/revision/latest?cb=20130109144647",
    damageType: "physical",
    damageBasic: "3D6+DM+1",
    damageBurst: null,
    ammoType: null,
    range: null,
    magazine: null,
    ammoPerShot: null,
    ammoPerBurst: null,
    basicApCost: 4,
    specialApCost: 6,
    minStrength: 3,
    place: 2,
    weight: 2,
    value: 200,
    frequency: 5,
    skill: "blunt",
    knowledges: ["kBluntWeapons", "kOneHandedWeapons"],
    tags: ["arme légère", "arme blanche"]
  },
  machete: {
    id: "machete",
    label: "Machette",
    img: "https://vignette.wikia.nocookie.net/fallout/images/5/5f/Tactics_machete.png/revision/latest?cb=20130109002538",
    damageType: "physical",
    damageBasic: "3D6+DM+2",
    damageBurst: null,
    ammoType: null,
    range: null,
    magazine: null,
    ammoPerShot: null,
    ammoPerBurst: null,
    basicApCost: 4,
    specialApCost: 6,
    minStrength: 3,
    place: 1.5,
    weight: 2,
    value: 130,
    frequency: 3,
    skill: "blunt",
    knowledges: ["kBladedWeapons", "kOneHandedWeapons"],
    tags: ["arme moyenne", "arme blanche"]
  },
  wakizachi: {
    id: "wakizachi",
    label: "Wakizachi",
    img: "https://vignette.wikia.nocookie.net/fallout/images/7/7a/Wknife.gif/revision/latest?cb=20150425212436",
    damageType: "physical",
    damageBasic: "3D6+DM+4",
    damageBurst: null,
    ammoType: null,
    range: null,
    magazine: null,
    ammoPerShot: null,
    ammoPerBurst: null,
    basicApCost: 4,
    specialApCost: 6,
    minStrength: 3,
    place: 2,
    weight: 1,
    value: 950,
    frequency: 2,
    skill: "blunt",
    knowledges: ["kBladedWeapons", "kOneHandedWeapons"],
    tags: ["arme moyenne", "arme blanche"]
  },
  ripper: {
    id: "ripper",
    label: "Ripper",
    img: "https://vignette.wikia.nocookie.net/fallout/images/e/e5/Tactics_ripper.png/revision/latest?cb=20130109134302",
    damageType: "physical",
    damageBasic: "3D6+DM+6",
    damageBurst: null,
    ammoType: null,
    range: null,
    magazine: null,
    ammoPerShot: null,
    ammoPerBurst: null,
    basicApCost: 4,
    specialApCost: 6,
    minStrength: 3,
    place: 1,
    weight: 1,
    value: 1500,
    frequency: 1,
    skill: "blunt",
    knowledges: ["kTwoHandedWeapons", "kBladedWeapons"],
    tags: ["arme moyenne", "arme blanche"]
  },
  chainsaw: {
    id: "chainsaw",
    label: "Tronçonneuse",
    img: "https://vignette.wikia.nocookie.net/fallout/images/5/5b/Chainsaw76.png/revision/latest/scale-to-width-down/242?cb=20190930060518",
    damageType: "physical",
    damageBasic: "3D6+DM+7",
    damageBurst: null,
    ammoType: "gas",
    range: null,
    magazine: 200,
    ammoPerShot: 1,
    ammoPerBurst: null,
    basicApCost: 4,
    specialApCost: 6,
    minStrength: 4,
    place: 3,
    weight: 3,
    value: 900,
    frequency: 2,
    skill: "blunt",
    knowledges: ["kTwoHandedWeapons", "kBladedWeapons"],
    tags: ["arme moyenne", "arme blanche", "spécial"]
  },
  electricHammer: {
    id: "electricHammer",
    label: "Marteau Electrique",
    img: "https://vignette.wikia.nocookie.net/fallout/images/2/21/SUPERSLEDGE.png/revision/latest/scale-to-width-down/242?cb=20110210214551",
    damageType: "other",
    damageBasic: "3D6+DM+8",
    damageBurst: null,
    ammoType: "energyCell",
    range: null,
    magazine: 100,
    ammoPerShot: 1,
    ammoPerBurst: null,
    basicApCost: 4,
    specialApCost: 6,
    minStrength: 4,
    place: 2,
    weight: 2,
    value: 2500,
    frequency: 2,
    skill: "blunt",
    knowledges: ["kTwoHandedWeapons", "kEnergyWeapons", "kBluntWeapons"],
    tags: ["arme lourde", "arme blanche", "arme à énergie"]
  },
  sldgeHammer: {
    id: "sldgeHammer",
    label: "Massue",
    img: "https://vignette.wikia.nocookie.net/fallout/images/3/30/Fo1_Sledgehammer.png/revision/latest?cb=20110429025337",
    damageType: "physical",
    damageBasic: "2D6+DM+5",
    damageBurst: null,
    ammoType: null,
    range: null,
    magazine: null,
    ammoPerShot: null,
    ammoPerBurst: null,
    basicApCost: 4,
    specialApCost: 6,
    minStrength: 4,
    place: 2,
    weight: 3,
    value: 1000,
    frequency: 4,
    skill: "blunt",
    knowledges: ["kTwoHandedWeapons", "kBluntWeapons"],
    tags: ["arme lourde", "arme blanche"]
  },
  superSledge: {
    id: "superSledge",
    label: "Super-Massue",
    img: "https://vignette.wikia.nocookie.net/fallout/images/5/52/Fo1_Super_Sledge.png/revision/latest?cb=20110430083915",
    damageType: "physical",
    damageBasic: "4D6+DM+10",
    damageBurst: null,
    ammoType: "energyCell",
    range: null,
    magazine: 100,
    ammoPerShot: 1,
    ammoPerBurst: null,
    basicApCost: 4,
    specialApCost: 6,
    minStrength: 5,
    place: 4,
    weight: 5,
    value: 3500,
    frequency: 1,
    skill: "blunt",
    knowledges: ["kTwoHandedWeapons", "kEnergyWeapons", "kBluntWeapons"],
    tags: ["arme lourde", "arme blanche", "arme à énergie"]
  },
  crossbow: {
    id: "crossbow",
    label: "Arbalète",
    img: "https://vignette.wikia.nocookie.net/fallout/images/e/e6/FO76_Crossbow.png/revision/latest/scale-to-width-down/242?cb=20191003045915",
    damageType: "physical",
    damageBasic: "3D6",
    damageBurst: null,
    ammoType: "bolt",
    range: 150,
    magazine: 1,
    ammoPerShot: 1,
    ammoPerBurst: null,
    basicApCost: 4,
    specialApCost: 6,
    minStrength: 4,
    place: 2,
    weight: 2,
    value: 300,
    frequency: 4,
    skill: "throw",
    knowledges: ["kTwoHandedWeapons", "kThrowingWeapons"],
    tags: ["arme moyenne", "arme de jet"]
  },
  boomerang: {
    id: "boomerang",
    label: "Boomerang",
    img: "https://vignette.wikia.nocookie.net/fallout/images/c/ca/FoT_boomerang.png/revision/latest?cb=20130110135955",
    damageType: "physical",
    damageBasic: "2D6",
    damageBurst: null,
    ammoType: null,
    range: 35,
    magazine: null,
    ammoPerShot: null,
    ammoPerBurst: null,
    basicApCost: 3,
    specialApCost: null,
    minStrength: 4,
    place: 1,
    weight: 0.5,
    value: 50,
    frequency: 3,
    skill: "throw",
    knowledges: ["kThrowingWeapons", "kOneHandedWeapons"],
    tags: ["arme légère", "arme de jet"]
  },
  molotof: {
    id: "molotof",
    label: "Molotof",
    img: "https://vignette.wikia.nocookie.net/fallout/images/b/b3/FoT_Molotov_cocktail.png/revision/latest?cb=20130110141124",
    damageType: "fire",
    damageBasic: "3D6+2",
    damageBurst: null,
    ammoType: null,
    range: 15,
    magazine: null,
    ammoPerShot: null,
    ammoPerBurst: null,
    basicApCost: 3,
    specialApCost: null,
    minStrength: 3,
    place: 1,
    weight: 0.5,
    value: 75,
    frequency: 5,
    skill: "throw",
    knowledges: ["kThrowingWeapons", "kOneHandedWeapons"],
    tags: ["arme de jet", "spécial"]
  },
  dart: {
    id: "dart",
    label: "Fléchette",
    img: "https://vignette.wikia.nocookie.net/fallout/images/3/38/FoT_dart.png/revision/latest?cb=20130110140912",
    damageType: "physical",
    damageBasic: "1D6+DM+2",
    damageBurst: null,
    ammoType: null,
    range: 15,
    magazine: null,
    ammoPerShot: null,
    ammoPerBurst: null,
    basicApCost: 3,
    specialApCost: 5,
    minStrength: 3,
    place: 0.5,
    weight: 0.1,
    value: 10,
    frequency: 5,
    skill: "throw",
    knowledges: ["kThrowingWeapons", "kOneHandedWeapons"],
    tags: ["arme de jet"]
  },
  throwingKnife: {
    id: "throwingKnife",
    label: "Couteau de lancer",
    img: "https://vignette.wikia.nocookie.net/fallout/images/2/2e/Tactics_throwing_knife.png/revision/latest?cb=20130110222742",
    damageType: "physical",
    damageBasic: "1D6+DM+3",
    damageBurst: null,
    ammoType: null,
    range: 15,
    magazine: null,
    ammoPerShot: null,
    ammoPerBurst: null,
    basicApCost: 3,
    specialApCost: 5,
    minStrength: 3,
    place: 0.5,
    weight: 0.1,
    value: 50,
    frequency: 5,
    skill: "throw",
    knowledges: ["kThrowingWeapons", "kOneHandedWeapons"],
    tags: ["arme de jet"]
  },
  shuriken: {
    id: "shuriken",
    label: "Shuriken",
    img: "https://vignette.wikia.nocookie.net/fallout/images/4/4b/Throwing_star.png/revision/latest?cb=20130110141727",
    damageType: "physical",
    damageBasic: "1D6+DM+6",
    damageBurst: null,
    ammoType: null,
    range: 15,
    magazine: null,
    ammoPerShot: null,
    ammoPerBurst: null,
    basicApCost: 3,
    specialApCost: 5,
    minStrength: 3,
    place: 0.5,
    weight: 0.1,
    value: 100,
    frequency: 4,
    skill: "throw",
    knowledges: ["kThrowingWeapons", "kOneHandedWeapons"],
    tags: ["arme de jet"]
  },
  fantasyBall: {
    id: "fantasyBall",
    label: "Sphère métamorphe",
    img: "https://vignette.wikia.nocookie.net/fallout/images/0/00/FoT_fantasyball.png/revision/latest?cb=20130110141302",
    damageType: "physical",
    damageBasic: "1D6+DM+8",
    damageBurst: null,
    ammoType: null,
    range: 15,
    magazine: null,
    ammoPerShot: null,
    ammoPerBurst: null,
    basicApCost: 3,
    specialApCost: 5,
    minStrength: 3,
    place: 0.5,
    weight: 0.5,
    value: 700,
    frequency: 2,
    skill: "throw",
    knowledges: ["kThrowingWeapons", "kOneHandedWeapons"],
    tags: ["arme de jet", "spécial"]
  },
  flashGrenade: {
    id: "flashGrenade",
    label: "Grenade aveuglante",
    img: "https://vignette.wikia.nocookie.net/fallout/images/6/60/FoT_flash_grenade.png/revision/latest?cb=20130109012020",
    damageType: "other",
    damageBasic: "1D6",
    damageBurst: null,
    ammoType: null,
    range: 10,
    magazine: null,
    ammoPerShot: null,
    ammoPerBurst: null,
    basicApCost: 6,
    specialApCost: null,
    minStrength: 3,
    place: 0.5,
    weight: 0.5,
    value: 250,
    frequency: 3,
    skill: "throw",
    knowledges: ["kThrowingWeapons", "kOneHandedWeapons"],
    tags: ["arme de jet", "spécial"]
  },
  fragGrenade: {
    id: "fragGrenade",
    label: "Grenade à fragmentation",
    img: "https://vignette.wikia.nocookie.net/fallout/images/8/84/FoT_frag_grenade.png/revision/latest?cb=20130109012349",
    damageType: "physical",
    damageBasic: "5D6+15",
    damageBurst: null,
    ammoType: null,
    range: 5,
    magazine: null,
    ammoPerShot: null,
    ammoPerBurst: null,
    basicApCost: 6,
    specialApCost: null,
    minStrength: 3,
    place: 0.5,
    weight: 0.5,
    value: 300,
    frequency: 4,
    skill: "throw",
    knowledges: ["kThrowingWeapons", "kOneHandedWeapons"],
    tags: ["arme de jet", "explosif"]
  },
  incendiaryGenade: {
    id: "incendiaryGenade",
    label: "Grenade incendiaire",
    img: "https://vignette.wikia.nocookie.net/fallout/images/9/9f/IncendiaryGrenadeTactics.png/revision/latest?cb=20130109013134",
    damageType: "fire",
    damageBasic: "5D6+8",
    damageBurst: null,
    ammoType: null,
    range: 5,
    magazine: null,
    ammoPerShot: null,
    ammoPerBurst: null,
    basicApCost: 6,
    specialApCost: null,
    minStrength: 3,
    place: 0.5,
    weight: 0.5,
    value: 500,
    frequency: 2,
    skill: "throw",
    knowledges: ["kThrowingWeapons", "kOneHandedWeapons"],
    tags: ["arme de jet", "spécial"]
  },
  acidGenade: {
    id: "acidGenade",
    label: "Grenade à acide",
    img: "https://vignette.wikia.nocookie.net/fallout/images/d/da/FoT_acid_grenade.png/revision/latest?cb=20130109011139",
    damageType: "other",
    damageBasic: "8D6+10",
    damageBurst: null,
    ammoType: null,
    range: 5,
    magazine: null,
    ammoPerShot: null,
    ammoPerBurst: null,
    basicApCost: 6,
    specialApCost: null,
    minStrength: 3,
    place: 0.5,
    weight: 0.5,
    value: 1500,
    frequency: 1,
    skill: "throw",
    knowledges: ["kThrowingWeapons", "kOneHandedWeapons"],
    tags: ["arme de jet", "spécial"]
  },
  iemGrenade: {
    id: "iemGrenade",
    label: "Grenade à IEM",
    img: "https://vignette.wikia.nocookie.net/fallout/images/a/a4/PulseGrenadeTactics.png/revision/latest?cb=20130109013643",
    damageType: "other",
    damageBasic: "6D6+20",
    damageBurst: null,
    ammoType: null,
    range: 10,
    magazine: null,
    ammoPerShot: null,
    ammoPerBurst: null,
    basicApCost: 6,
    specialApCost: null,
    minStrength: 3,
    place: 0.5,
    weight: 0.5,
    value: 1200,
    frequency: 2,
    skill: "throw",
    knowledges: ["kThrowingWeapons", "kEnergyWeapons", "kOneHandedWeapons"],
    tags: ["spécial", "arme de jet"]
  },
  plasmaGrenade: {
    id: "plasmaGrenade",
    label: "Grenade à plasma",
    img: "https://vignette.wikia.nocookie.net/fallout/images/2/2f/FoT_plasma_grenade.png/revision/latest?cb=20130109013430",
    damageType: "plasma",
    damageBasic: "8D6+10",
    damageBurst: null,
    ammoType: null,
    range: 5,
    magazine: null,
    ammoPerShot: null,
    ammoPerBurst: null,
    basicApCost: 6,
    specialApCost: null,
    minStrength: 3,
    place: 0.5,
    weight: 0.5,
    value: 1000,
    frequency: 2,
    skill: "throw",
    knowledges: ["kThrowingWeapons", "kEnergyWeapons", "kOneHandedWeapons"],
    tags: ["arme de jet", "arme à énergie"]
  },
  puffer: {
    id: "puffer",
    label: "Piège à spores",
    img: "https://vignette.wikia.nocookie.net/fallout/images/c/c5/FOT_puffer.png/revision/latest?cb=20130107221025",
    damageType: "physical",
    damageBasic: "2D6+10",
    damageBurst: null,
    ammoType: null,
    range: 3,
    magazine: null,
    ammoPerShot: null,
    ammoPerBurst: null,
    basicApCost: null,
    specialApCost: null,
    minStrength: null,
    place: 1,
    weight: 1,
    value: 50,
    frequency: 4,
    skill: "trap",
    knowledges: [],
    tags: ["piège", "spécial"]
  },
  c4: {
    id: "c4",
    label: "C4",
    img: "https://vignette.wikia.nocookie.net/fallout/images/d/d6/Fo1_Plastic_Explosives_Armed.png/revision/latest?cb=20110429011936",
    damageType: "physical",
    damageBasic: "5D6+10",
    damageBurst: null,
    ammoType: null,
    range: 1,
    magazine: null,
    ammoPerShot: null,
    ammoPerBurst: null,
    basicApCost: null,
    specialApCost: null,
    minStrength: null,
    place: 1,
    weight: 1,
    value: 80,
    frequency: 3,
    skill: "trap",
    knowledges: [],
    tags: ["piège", "explosif"]
  },
  plastic: {
    id: "plastic",
    label: "Plastic militaire",
    img: "https://vignette.wikia.nocookie.net/fallout/images/2/20/PlasticTactics.png/revision/latest?cb=20130109010120",
    damageType: "physical",
    damageBasic: "5D6+40",
    damageBurst: null,
    ammoType: null,
    range: 5,
    magazine: null,
    ammoPerShot: null,
    ammoPerBurst: null,
    basicApCost: null,
    specialApCost: null,
    minStrength: null,
    place: 1,
    weight: 1,
    value: 200,
    frequency: 2,
    skill: "trap",
    knowledges: [],
    tags: ["piège", "explosif"]
  },
  claymore: {
    id: "claymore",
    label: "Claymore",
    img: "https://vignette.wikia.nocookie.net/fallout/images/d/d2/FOTclaymore.png/revision/latest?cb=20130111174003",
    damageType: "physical",
    damageBasic: "8D6+25",
    damageBurst: null,
    ammoType: null,
    range: 5,
    magazine: null,
    ammoPerShot: null,
    ammoPerBurst: null,
    basicApCost: null,
    specialApCost: null,
    minStrength: null,
    place: 1.5,
    weight: 1,
    value: 300,
    frequency: 2,
    skill: "trap",
    knowledges: [],
    tags: ["piège", "explosif"]
  },
  dynamite: {
    id: "dynamite",
    label: "Dynamite",
    img: "https://vignette.wikia.nocookie.net/fallout/images/5/50/Fo1_Dynamite.png/revision/latest?cb=20110307011343",
    damageType: "physical",
    damageBasic: "10D6+35",
    damageBurst: null,
    ammoType: null,
    range: 10,
    magazine: null,
    ammoPerShot: null,
    ammoPerBurst: null,
    basicApCost: null,
    specialApCost: null,
    minStrength: null,
    place: 1,
    weight: 1,
    value: 150,
    frequency: 4,
    skill: "trap",
    knowledges: [],
    tags: ["piège", "explosif"]
  },
  explosiveTrap: {
    id: "explosiveTrap",
    label: "Piège explosif",
    img: "https://vignette.wikia.nocookie.net/fallout/images/8/8a/FOTremotedettrap.png/revision/latest?cb=20130107221557",
    damageType: "physical",
    damageBasic: "6D6+15",
    damageBurst: null,
    ammoType: null,
    range: 3,
    magazine: null,
    ammoPerShot: null,
    ammoPerBurst: null,
    basicApCost: null,
    specialApCost: null,
    minStrength: null,
    place: 1.5,
    weight: 1,
    value: 250,
    frequency: 3,
    skill: "trap",
    knowledges: [],
    tags: ["piège", "explosif"]
  },
  acidMineT86: {
    id: "acidMineT86",
    label: "Mine à acide T86",
    img: "https://vignette.wikia.nocookie.net/fallout/images/5/51/FOTT86acid.png/revision/latest?cb=20130109004836",
    damageType: "other",
    damageBasic: "8D6+30",
    damageBurst: null,
    ammoType: null,
    range: 3,
    magazine: null,
    ammoPerShot: null,
    ammoPerBurst: null,
    basicApCost: null,
    specialApCost: null,
    minStrength: null,
    place: 1.5,
    weight: 1.5,
    value: 500,
    frequency: 2,
    skill: "trap",
    knowledges: [],
    tags: ["piège", "spécial"]
  },
  t13mine: {
    id: "t13mine",
    label: "Mine antipersonnelle T13",
    img: "https://vignette.wikia.nocookie.net/fallout/images/6/66/FOTT13mine.png/revision/latest?cb=20131011161847",
    damageType: "physical",
    damageBasic: "9D6+20",
    damageBurst: null,
    ammoType: null,
    range: 1,
    magazine: null,
    ammoPerShot: null,
    ammoPerBurst: null,
    basicApCost: null,
    specialApCost: null,
    minStrength: null,
    place: 1.5,
    weight: 1.5,
    value: 250,
    frequency: 2,
    skill: "trap",
    knowledges: [],
    tags: ["piège", "explosif"]
  },
  iemMine: {
    id: "iemMine",
    label: "Mine IEM",
    img: "https://vignette.wikia.nocookie.net/fallout/images/0/01/PulseMine.png/revision/latest/scale-to-width-down/242?cb=20110209085130",
    damageType: "other",
    damageBasic: "10D6+30",
    damageBurst: null,
    ammoType: null,
    range: 3,
    magazine: null,
    ammoPerShot: null,
    ammoPerBurst: null,
    basicApCost: null,
    specialApCost: null,
    minStrength: null,
    place: 1.5,
    weight: 0.5,
    value: 1500,
    frequency: 2,
    skill: "trap",
    knowledges: ["kEnergyWeapons"],
    tags: ["piège", "arme à énergie"]
  },
  t45SEMine: {
    id: "t45SEMine",
    label: "Mine antipersonnelle T45 SE",
    img: "https://vignette.wikia.nocookie.net/fallout/images/b/b8/FOTT455Emine.png/revision/latest?cb=20131016052302",
    damageType: "physical",
    damageBasic: "10D6+30",
    damageBurst: null,
    ammoType: null,
    range: 3,
    magazine: null,
    ammoPerShot: null,
    ammoPerBurst: null,
    basicApCost: null,
    specialApCost: null,
    minStrength: null,
    place: 2,
    weight: 3,
    value: 400,
    frequency: 2,
    skill: "trap",
    knowledges: [],
    tags: ["piège", "explosif"]
  }
}

export default weaponsMap
