import { Clothing, ClothingId } from "./clothing-types"

const clothings: Record<ClothingId, Clothing> = {
  // NON-MARTIAL CLOTHINGS
  prewarHat: {
    id: "prewarHat",
    label: "Chapeau d'avant guerre",
    type: "light",
    armorClass: 1,
    threshold: 1,
    physicalDamageResist: 1,
    laserDamageResist: 1,
    fireDamageResist: 1,
    plasmaDamageResist: 1,
    protects: ["head"],
    malus: -0,
    place: 1.5,
    weight: 0.4,
    value: 60,
    symptoms: [
      { id: "barter", operation: "add", value: 5 },
      { id: "speech", operation: "add", value: 5 }
    ]
  },
  prewarSuit: {
    id: "prewarSuit",
    label: "Costume d'avant guerre",
    type: "light",
    armorClass: 1,
    threshold: 1,
    physicalDamageResist: 1,
    laserDamageResist: 1,
    fireDamageResist: 1,
    plasmaDamageResist: 1,
    protects: ["torso", "arms", "legs"],
    malus: -0,
    place: 4,
    weight: 1,
    value: 350,
    symptoms: [
      { id: "barter", operation: "add", value: 10 },
      { id: "speech", operation: "add", value: 10 }
    ]
  },
  cowboyHat: {
    id: "cowboyHat",
    label: "Chapeau de cowboy",
    type: "light",
    armorClass: 1,
    threshold: 1,
    physicalDamageResist: 1,
    laserDamageResist: 1,
    fireDamageResist: 1,
    plasmaDamageResist: 1,
    protects: ["head"],
    malus: -0,
    place: 2,
    weight: 0.5,
    value: 60,
    symptoms: []
  },
  desperadoHat: {
    id: "desperadoHat",
    label: "Chapeau de desperado",
    type: "light",
    armorClass: 1,
    threshold: 1,
    physicalDamageResist: 1,
    laserDamageResist: 1,
    fireDamageResist: 1,
    plasmaDamageResist: 1,
    protects: ["head"],
    malus: -0,
    place: 2,
    weight: 0.5,
    value: 150,
    symptoms: [
      { id: "lightMedWeapons", operation: "add", value: 10 },
      { id: "survival", operation: "add", value: 10 }
    ]
  },
  // MARTIAL CLOTHINGS
  leatherJacket: {
    id: "leatherJacket",
    label: "Veste en cuir",
    type: "light",
    armorClass: 5,
    threshold: 1,
    physicalDamageResist: 5,
    laserDamageResist: 5,
    fireDamageResist: 5,
    plasmaDamageResist: 5,
    protects: ["torso", "arms"],
    malus: -0,
    place: 2.5,
    weight: 2,
    value: 250,
    symptoms: [{ id: "armorClass", operation: "add", value: 5 }]
  },
  geckoHide: {
    id: "geckoHide",
    label: "Tenue peau de gecko",
    type: "light",
    armorClass: 3,
    threshold: 1,
    physicalDamageResist: 5,
    laserDamageResist: 5,
    fireDamageResist: 5,
    plasmaDamageResist: 5,
    protects: ["torso"],
    malus: -0,
    place: 2.5,
    weight: 2,
    value: 500,
    symptoms: [
      { id: "armorClass", operation: "add", value: 3 },
      { id: "stealth", operation: "add", value: 5 },
      { id: "speech", operation: "add", value: -10 }
    ]
  },
  combatJacket: {
    id: "combatJacket",
    label: "Veste de combat",
    type: "light",
    armorClass: 7,
    threshold: 2,
    physicalDamageResist: 10,
    laserDamageResist: 10,
    fireDamageResist: 10,
    plasmaDamageResist: 10,
    protects: ["torso", "arms"],
    malus: -0,
    place: 3,
    weight: 3,
    value: 600,
    symptoms: [{ id: "armorClass", operation: "add", value: 7 }]
  },
  leatherArmor: {
    id: "leatherArmor",
    label: "Armure de cuir",
    type: "light",
    armorClass: 15,
    threshold: 5,
    physicalDamageResist: 20,
    laserDamageResist: 15,
    fireDamageResist: 15,
    plasmaDamageResist: 10,
    protects: ["torso", "arms"],
    malus: -5,
    place: 5,
    weight: 5,
    value: 1000,
    symptoms: [
      { id: "armorClass", operation: "add", value: 15 },
      { id: "stealth", operation: "add", value: -5 },
      { id: "throw", operation: "add", value: -5 },
      { id: "manipulation", operation: "add", value: -5 },
      { id: "trap", operation: "add", value: -5 },
      { id: "physical", operation: "add", value: -5 },
      { id: "aid", operation: "add", value: -5 },
      { id: "steal", operation: "add", value: -5 }
    ]
  },
  raiderLightArmor: {
    id: "raiderLightArmor",
    label: "Armure de Raider",
    type: "light",
    armorClass: 15,
    threshold: 5,
    physicalDamageResist: 20,
    laserDamageResist: 15,
    fireDamageResist: 15,
    plasmaDamageResist: 10,
    protects: ["torso", "arms"],
    malus: -5,
    place: 5,
    weight: 5,
    value: 400,
    symptoms: [
      { id: "armorClass", operation: "add", value: 15 },
      { id: "barter", operation: "add", value: -5 },
      { id: "speech", operation: "add", value: -5 },
      { id: "throw", operation: "add", value: -5 },
      { id: "manipulation", operation: "add", value: -5 },
      { id: "trap", operation: "add", value: -5 },
      { id: "physical", operation: "add", value: -5 },
      { id: "aid", operation: "add", value: -5 },
      { id: "steal", operation: "add", value: -5 }
    ]
  },
  leatherArmorII: {
    id: "leatherArmorII",
    label: "Armure de cuir II",
    type: "light",
    armorClass: 18,
    threshold: 6,
    physicalDamageResist: 25,
    laserDamageResist: 20,
    fireDamageResist: 20,
    plasmaDamageResist: 10,
    protects: ["torso", "arms"],
    malus: -5,
    place: 5,
    weight: 6,
    value: 1400,
    symptoms: [
      { id: "armorClass", operation: "add", value: 18 },
      { id: "stealth", operation: "add", value: -5 },
      { id: "throw", operation: "add", value: -5 },
      { id: "manipulation", operation: "add", value: -5 },
      { id: "trap", operation: "add", value: -5 },
      { id: "physical", operation: "add", value: -5 },
      { id: "aid", operation: "add", value: -5 },
      { id: "steal", operation: "add", value: -5 }
    ]
  },
  raiderLightArmorII: {
    id: "raiderLightArmorII",
    label: "Armure de Raider II",
    type: "light",
    armorClass: 18,
    threshold: 6,
    physicalDamageResist: 25,
    laserDamageResist: 20,
    fireDamageResist: 20,
    plasmaDamageResist: 10,
    protects: ["torso", "arms"],
    malus: -5,
    place: 5,
    weight: 6,
    value: 800,
    symptoms: [
      { id: "armorClass", operation: "add", value: 18 },
      { id: "barter", operation: "add", value: -5 },
      { id: "speech", operation: "add", value: -5 },
      { id: "throw", operation: "add", value: -5 },
      { id: "manipulation", operation: "add", value: -5 },
      { id: "trap", operation: "add", value: -5 },
      { id: "physical", operation: "add", value: -5 },
      { id: "aid", operation: "add", value: -5 },
      { id: "steal", operation: "add", value: -5 }
    ]
  },
  bioArmor: {
    id: "bioArmor",
    label: "Armure biologique",
    type: "light",
    armorClass: 8,
    threshold: 1,
    physicalDamageResist: 10,
    laserDamageResist: 10,
    fireDamageResist: 20,
    plasmaDamageResist: 10,
    protects: ["torso", "arms", "legs", "head", "groin"],
    malus: -15,
    place: 7,
    weight: 5,
    value: 1500,
    symptoms: [
      { id: "armorClass", operation: "add", value: 8 },
      { id: "radRes", operation: "mult", value: 0.2 },
      { id: "stealth", operation: "add", value: -15 },
      { id: "throw", operation: "add", value: -15 },
      { id: "manipulation", operation: "add", value: -15 },
      { id: "trap", operation: "add", value: -15 },
      { id: "physical", operation: "add", value: -15 },
      { id: "aid", operation: "add", value: -15 },
      { id: "steal", operation: "add", value: -15 }
    ]
  },
  mutieArmor: {
    id: "mutieArmor",
    label: "Armure de mutant",
    type: "light",
    armorClass: 15,
    threshold: 5,
    physicalDamageResist: 25,
    laserDamageResist: 20,
    fireDamageResist: 20,
    plasmaDamageResist: 10,
    protects: ["torso"],
    malus: -5,
    place: 8,
    weight: 12,
    value: 1800,
    symptoms: [
      { id: "armorClass", operation: "add", value: 15 },
      { id: "stealth", operation: "add", value: -5 },
      { id: "throw", operation: "add", value: -5 },
      { id: "manipulation", operation: "add", value: -5 },
      { id: "trap", operation: "add", value: -5 },
      { id: "physical", operation: "add", value: -5 },
      { id: "aid", operation: "add", value: -5 },
      { id: "steal", operation: "add", value: -5 }
    ]
  },
  helmet: {
    id: "helmet",
    label: "Casque",
    type: "light",
    armorClass: 5,
    threshold: 5,
    physicalDamageResist: 30,
    laserDamageResist: 10,
    fireDamageResist: 10,
    plasmaDamageResist: 10,
    protects: ["head"],
    malus: -3,
    place: 1,
    weight: 1,
    value: 300,
    symptoms: [
      { id: "armorClass", operation: "add", value: 5 },
      { id: "stealth", operation: "add", value: -3 },
      { id: "perceptionSkill", operation: "add", value: -3 },
      { id: "trap", operation: "add", value: -3 },
      { id: "aid", operation: "add", value: -3 }
    ]
  },
  raiderHelmet: {
    id: "raiderHelmet",
    label: "Casque de Raider",
    type: "light",
    armorClass: 5,
    threshold: 5,
    physicalDamageResist: 30,
    laserDamageResist: 10,
    fireDamageResist: 10,
    plasmaDamageResist: 10,
    protects: ["head"],
    malus: -3,
    place: 1,
    weight: 1,
    value: 100,
    symptoms: [
      { id: "armorClass", operation: "add", value: 5 },
      { id: "barter", operation: "add", value: -3 },
      { id: "speech", operation: "add", value: -3 },
      { id: "perceptionSkill", operation: "add", value: -3 },
      { id: "trap", operation: "add", value: -3 },
      { id: "aid", operation: "add", value: -3 }
    ]
  },
  leatherLegArmor: {
    id: "leatherLegArmor",
    label: "Jambières en cuir",
    type: "light",
    armorClass: 5,
    threshold: 5,
    physicalDamageResist: 15,
    laserDamageResist: 10,
    fireDamageResist: 10,
    plasmaDamageResist: 10,
    protects: ["legs"],
    malus: -2,
    place: 1.5,
    weight: 1,
    value: 150,
    symptoms: [
      { id: "armorClass", operation: "add", value: 5 },
      { id: "stealth", operation: "add", value: -2 },
      { id: "throw", operation: "add", value: -2 },
      { id: "manipulation", operation: "add", value: -2 },
      { id: "trap", operation: "add", value: -2 },
      { id: "physical", operation: "add", value: -2 },
      { id: "aid", operation: "add", value: -2 },
      { id: "steal", operation: "add", value: -2 }
    ]
  },
  leatherArmArmor: {
    id: "leatherArmArmor",
    label: "Brassards en cuir",
    type: "light",
    armorClass: 5,
    threshold: 5,
    physicalDamageResist: 15,
    laserDamageResist: 10,
    fireDamageResist: 10,
    plasmaDamageResist: 10,
    protects: ["arms"],
    malus: -5,
    place: 1,
    weight: 1,
    value: 150,
    symptoms: [
      { id: "armorClass", operation: "add", value: 5 },
      { id: "stealth", operation: "add", value: -5 },
      { id: "throw", operation: "add", value: -5 },
      { id: "manipulation", operation: "add", value: -5 },
      { id: "trap", operation: "add", value: -5 },
      { id: "physical", operation: "add", value: -5 },
      { id: "aid", operation: "add", value: -5 },
      { id: "steal", operation: "add", value: -5 }
    ]
  },
  metalArmor: {
    id: "metalArmor",
    label: "Armure de métal",
    type: "medium",
    armorClass: 22,
    threshold: 7,
    physicalDamageResist: 30,
    laserDamageResist: 30,
    fireDamageResist: 10,
    plasmaDamageResist: 15,
    protects: ["torso", "arms"],
    malus: -10,
    place: 6,
    weight: 12,
    value: 2500,
    symptoms: [
      { id: "armorClass", operation: "add", value: 22 },
      { id: "stealth", operation: "add", value: -10 },
      { id: "throw", operation: "add", value: -10 },
      { id: "manipulation", operation: "add", value: -10 },
      { id: "trap", operation: "add", value: -10 },
      { id: "physical", operation: "add", value: -10 },
      { id: "aid", operation: "add", value: -10 },
      { id: "steal", operation: "add", value: -10 }
    ]
  },
  metalArmorII: {
    id: "metalArmorII",
    label: "Armure de métal II",
    type: "medium",
    armorClass: 25,
    threshold: 8,
    physicalDamageResist: 35,
    laserDamageResist: 35,
    fireDamageResist: 15,
    plasmaDamageResist: 20,
    protects: ["torso", "arms"],
    malus: -10,
    place: 7,
    weight: 14,
    value: 3000,
    symptoms: [
      { id: "armorClass", operation: "add", value: 25 },
      { id: "stealth", operation: "add", value: -10 },
      { id: "throw", operation: "add", value: -10 },
      { id: "manipulation", operation: "add", value: -10 },
      { id: "trap", operation: "add", value: -10 },
      { id: "physical", operation: "add", value: -10 },
      { id: "aid", operation: "add", value: -10 },
      { id: "steal", operation: "add", value: -10 }
    ]
  },
  combatArmor: {
    id: "combatArmor",
    label: "Armure de combat",
    type: "medium",
    armorClass: 30,
    threshold: 10,
    physicalDamageResist: 40,
    laserDamageResist: 40,
    fireDamageResist: 30,
    plasmaDamageResist: 25,
    protects: ["torso", "arms", "legs", "head", "groin"],
    malus: -25,
    place: 11,
    weight: 20,
    value: 4000,
    symptoms: [
      { id: "armorClass", operation: "add", value: 30 },
      { id: "stealth", operation: "add", value: -25 },
      { id: "throw", operation: "add", value: -25 },
      { id: "manipulation", operation: "add", value: -25 },
      { id: "trap", operation: "add", value: -25 },
      { id: "physical", operation: "add", value: -25 },
      { id: "aid", operation: "add", value: -25 },
      { id: "steal", operation: "add", value: -25 }
    ]
  },
  combatArmorII: {
    id: "combatArmorII",
    label: "Armure de combat II",
    type: "medium",
    armorClass: 33,
    threshold: 11,
    physicalDamageResist: 45,
    laserDamageResist: 45,
    fireDamageResist: 35,
    plasmaDamageResist: 30,
    protects: ["torso", "arms", "legs", "head", "groin"],
    malus: -25,
    place: 10,
    weight: 18,
    value: 5500,
    symptoms: [
      { id: "armorClass", operation: "add", value: 33 },
      { id: "stealth", operation: "add", value: -25 },
      { id: "throw", operation: "add", value: -25 },
      { id: "manipulation", operation: "add", value: -25 },
      { id: "trap", operation: "add", value: -25 },
      { id: "physical", operation: "add", value: -25 },
      { id: "aid", operation: "add", value: -25 },
      { id: "steal", operation: "add", value: -25 }
    ]
  },
  teslaArmor: {
    id: "teslaArmor",
    label: "Armure Tesla",
    type: "medium",
    armorClass: 30,
    threshold: 9,
    physicalDamageResist: 40,
    laserDamageResist: 80,
    fireDamageResist: 25,
    plasmaDamageResist: 75,
    protects: ["torso", "arms", "legs", "head", "groin"],
    malus: -20,
    place: 10,
    weight: 15,
    value: 6000,
    symptoms: [
      { id: "armorClass", operation: "add", value: 30 },
      { id: "stealth", operation: "add", value: -20 },
      { id: "throw", operation: "add", value: -20 },
      { id: "manipulation", operation: "add", value: -20 },
      { id: "trap", operation: "add", value: -20 },
      { id: "physical", operation: "add", value: -20 },
      { id: "aid", operation: "add", value: -20 },
      { id: "steal", operation: "add", value: -20 }
    ]
  },
  mutieArmorII: {
    id: "mutieArmorII",
    label: "Armure de mutant II",
    type: "medium",
    armorClass: 28,
    threshold: 10,
    physicalDamageResist: 40,
    laserDamageResist: 35,
    fireDamageResist: 20,
    plasmaDamageResist: 25,
    protects: ["torso", "arms", "legs", "head"],
    malus: -20,
    place: 15,
    weight: 25,
    value: 4600,
    symptoms: [
      { id: "armorClass", operation: "add", value: 28 },
      { id: "stealth", operation: "add", value: -20 },
      { id: "throw", operation: "add", value: -20 },
      { id: "manipulation", operation: "add", value: -20 },
      { id: "trap", operation: "add", value: -20 },
      { id: "physical", operation: "add", value: -20 },
      { id: "aid", operation: "add", value: -20 },
      { id: "steal", operation: "add", value: -20 }
    ]
  },
  mkI: {
    id: "mkI",
    label: "MK-II",
    type: "heavy",
    armorClass: 35,
    threshold: 15,
    physicalDamageResist: 50,
    laserDamageResist: 50,
    fireDamageResist: 40,
    plasmaDamageResist: 40,
    protects: ["torso", "arms", "legs", "head", "groin"],
    malus: -30,
    place: 15,
    weight: 43,
    value: 15000,
    symptoms: [
      { id: "armorClass", operation: "add", value: 35 },
      { id: "strength", operation: "add", value: 3 },
      { id: "recRad", operation: "mult", value: 0.01 },
      { id: "stealth", operation: "add", value: -30 },
      { id: "throw", operation: "add", value: -30 },
      { id: "manipulation", operation: "add", value: -30 },
      { id: "trap", operation: "add", value: -30 },
      { id: "physical", operation: "add", value: -30 },
      { id: "aid", operation: "add", value: -30 },
      { id: "steal", operation: "add", value: -30 }
    ]
  },
  mkII: {
    id: "mkII",
    label: "MK-IIB",
    type: "heavy",
    armorClass: 40,
    threshold: 18,
    physicalDamageResist: 55,
    laserDamageResist: 55,
    fireDamageResist: 50,
    plasmaDamageResist: 45,
    protects: ["torso", "arms", "legs", "head", "groin"],
    malus: -30,
    place: 15,
    weight: 48,
    value: 28000,
    symptoms: [
      { id: "armorClass", operation: "add", value: 40 },
      { id: "strength", operation: "add", value: 3 },
      { id: "recRad", operation: "mult", value: 0.01 },
      { id: "stealth", operation: "add", value: -30 },
      { id: "throw", operation: "add", value: -30 },
      { id: "manipulation", operation: "add", value: -30 },
      { id: "trap", operation: "add", value: -30 },
      { id: "physical", operation: "add", value: -30 },
      { id: "aid", operation: "add", value: -30 },
      { id: "steal", operation: "add", value: -30 }
    ]
  },
  mkc: {
    id: "mkc",
    label: "MK-CI",
    type: "heavy",
    armorClass: 38,
    threshold: 20,
    physicalDamageResist: 55,
    laserDamageResist: 50,
    fireDamageResist: 40,
    plasmaDamageResist: 45,
    protects: ["torso", "arms", "legs", "head", "groin"],
    malus: -30,
    place: 15,
    weight: 45,
    value: 21000,
    symptoms: [
      { id: "armorClass", operation: "add", value: 38 },
      { id: "strength", operation: "add", value: 3 },
      { id: "recRad", operation: "mult", value: 0.01 },
      { id: "stealth", operation: "add", value: -30 },
      { id: "throw", operation: "add", value: -30 },
      { id: "manipulation", operation: "add", value: -30 },
      { id: "trap", operation: "add", value: -30 },
      { id: "physical", operation: "add", value: -30 },
      { id: "aid", operation: "add", value: -30 },
      { id: "steal", operation: "add", value: -30 }
    ]
  },
  mkcI: {
    id: "mkcI",
    label: "MK-CII",
    type: "heavy",
    armorClass: 43,
    threshold: 25,
    physicalDamageResist: 65,
    laserDamageResist: 55,
    fireDamageResist: 55,
    plasmaDamageResist: 50,
    protects: ["torso", "arms", "legs", "head", "groin"],
    malus: -30,
    place: 15,
    weight: 40,
    value: 34000,
    symptoms: [
      { id: "armorClass", operation: "add", value: 43 },
      { id: "strength", operation: "add", value: 3 },
      { id: "recRad", operation: "mult", value: 0.01 },
      { id: "stealth", operation: "add", value: -30 },
      { id: "throw", operation: "add", value: -30 },
      { id: "manipulation", operation: "add", value: -30 },
      { id: "trap", operation: "add", value: -30 },
      { id: "physical", operation: "add", value: -30 },
      { id: "aid", operation: "add", value: -30 },
      { id: "steal", operation: "add", value: -30 }
    ]
  },
  mkaI: {
    id: "mkaI",
    label: "MK-AI",
    type: "heavy",
    armorClass: 40,
    threshold: 23,
    physicalDamageResist: 55,
    laserDamageResist: 55,
    fireDamageResist: 45,
    plasmaDamageResist: 45,
    protects: ["torso", "arms", "legs", "head", "groin"],
    malus: -30,
    place: 17,
    weight: 50,
    value: 25000,
    symptoms: [
      { id: "armorClass", operation: "add", value: 40 },
      { id: "strength", operation: "add", value: 3 },
      { id: "recRad", operation: "mult", value: 0.01 },
      { id: "stealth", operation: "add", value: -30 },
      { id: "throw", operation: "add", value: -30 },
      { id: "manipulation", operation: "add", value: -30 },
      { id: "trap", operation: "add", value: -30 },
      { id: "physical", operation: "add", value: -30 },
      { id: "aid", operation: "add", value: -30 },
      { id: "steal", operation: "add", value: -30 }
    ]
  },
  mkaII: {
    id: "mkaII",
    label: "MK-AII",
    type: "heavy",
    armorClass: 45,
    threshold: 26,
    physicalDamageResist: 60,
    laserDamageResist: 60,
    fireDamageResist: 60,
    plasmaDamageResist: 60,
    protects: ["torso", "arms", "legs", "head", "groin"],
    malus: -30,
    place: 17,
    weight: 55,
    value: 40000,
    symptoms: [
      { id: "armorClass", operation: "add", value: 45 },
      { id: "strength", operation: "add", value: 4 },
      { id: "recRad", operation: "mult", value: 0.01 },
      { id: "stealth", operation: "add", value: -30 },
      { id: "throw", operation: "add", value: -30 },
      { id: "manipulation", operation: "add", value: -30 },
      { id: "trap", operation: "add", value: -30 },
      { id: "physical", operation: "add", value: -30 },
      { id: "aid", operation: "add", value: -30 },
      { id: "steal", operation: "add", value: -30 }
    ]
  }
}

export default clothings
